# Task 6.1 Open Data Set Selection and Wrangling

## Task 6.1 Script Contents

__1. Import libraries and data sets__  
__2. Clean the assisted housing (HUD) data set__  
__3. Clean the gun violence data set__  
__4. Clean the education data set__  
__5. Clean the unemployment data set__  
__6. Merge the data sets__  
__6.1 Create a common geolocator as a merge key and convert latitude and longitude to FIPS State/ County Codes__  
__6.2 Merge the assisted housing (HUD) and gun violence data sets__  
__6.3 Merge the education and unemployment data sets__  
__7. Export revised data sets__  

# 1.0 Import data libraries and data sets

## 1.1 Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

## 1.2 Import data sets

In [2]:
# Create a path to import and export data sets
path = r'/Users/brucehickling/Library/CloudStorage/Dropbox/Courses/CareerFoundry/Data Immersion/6_Advanced Analytics & Dashboard Design'

### 1.2.1 Import US Department of Housing and Urban Development (HUD) data set on assisted multifamily housing

In [3]:
df_HUD = pd.read_csv(os.path.join(path, '2_Data', 'Raw Data', 'HUD Multifamily Housing Assisted Properties.csv'), index_col=0) 

/var/folders/9d/wp_2lptx7pngxs5vccs361_c0000gn/T/ipykernel_1477/372777508.py:1: DtypeWarning: Columns (94,98,167,201,202,203,204,205,206,207,209,210,212,220,224) have mixed types. Specify dtype option on import or set low_memory=False.
  df_HUD = pd.read_csv(os.path.join(path, '2_Data', 'Raw Data', 'HUD Multifamily Housing Assisted Properties.csv'), index_col=0)


In [4]:
df_HUD.head()

X          Y  OBJECTID  PROPERTY_ID   UGLG_KEY HUB_NAME_TEXT  \
index                                                                         
0     -83.094242  40.309009         1    800000030  3921434.0       Detroit   
1     -86.143070  41.652389         2    800000031  1849932.0       Chicago   
2     -76.601014  39.309478         3    800000043  2404000.0     Baltimore   
3     -86.347000  38.367692         4    800000045  1846746.0       Chicago   
4     -87.703574  41.886009         5    800000046  1714000.0       Chicago   

      SERVICING_SITE_NAME_TEXT PROJECT_MANAGER_NAME_TEXT  \
index                                                      
0                      Detroit           DENISE WILLIAMS   
1                      Chicago        GERALDINE V DUPATY   
2                    Baltimore        CAROLYN M ANASTASI   
3                      Chicago            DAPHNE C LLOYD   
4                      Chicago     TANIKA MATHIS-EARSERY   

                         PROPERTY_NAME_TEXT      ADDRESS_LINE1_TEXT  ...  \
index                                                                ...   
0      DELAWARE  CREATIVE  HOUSING  HUD  II          560 Buehler Dr  ...   
1                       EASTGATE APARTMENTS        900 Roosevelt Dr  ...   
2             QUEEN ESTHER / LANVALE TOWERS       1300 E LANVALE ST  ...   
3          LHDC MARENGO HOUSING FOR ELDERLY  521 SOUTH SUGAR STREET  ...   
4                             MATTHEW MANOR        271 N Albany Ave  ...   

      TPOVERTY TPCT_OWNSFD CHLDRN_MBR_CNT ELDLY_PRCNT  PCT_DISABLED_LT62_ALL  \
index                                                                          
0        -4.00   -4.000000             -4   -4.000000              -4.000000   
1        10.79   90.260002              5   44.900002              22.450001   
2        31.40    3.110000             60   12.560000              30.490000   
3        16.16   76.220001              1   79.169998              12.500000   
4        28.73   11.100000              0   98.309998               0.000000   

       PCT_LT80_MEDIAN MEDIAN_INC_AMNT          LAST_UPDT_DTTM  \
index                                                            
0                 -4.0              -4  2022/01/06 19:10:36+00   
1                100.0           11640  2022/01/06 19:10:36+00   
2                100.0            9528  2022/01/06 19:10:36+00   
3                100.0           12960  2022/01/06 19:10:36+00   
4                100.0           10304  2022/01/06 19:10:36+00   

      ANNL_EXPNS_AMNT ANNL_EXPNS_AMNT_PREV_YR  
index                                          
0                  -4                    -4.0  
1              187156                180305.0  
2             1935342               1852369.0  
3              210453                216625.0  
4              588277                596380.0  

[5 rows x 286 columns]

In [5]:
df_HUD.shape

(23634, 286)

In [6]:
df_HUD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23634 entries, 0 to 23633
Columns: 286 entries, X to ANNL_EXPNS_AMNT_PREV_YR
dtypes: float64(87), int64(38), object(161)
memory usage: 51.7+ MB


### 1.2.2 Import Gun Violence data set

In [7]:
df_gun = pd.read_csv(os.path.join(path, '2_Data', 'Raw Data', 'gun-violence-data_01-2013_03-2018.csv'), index_col=0)

In [8]:
df_gun.head()

date           state city_or_county  \
incident_id                                              
461105       2013-01-01    Pennsylvania     Mckeesport   
460726       2013-01-01      California      Hawthorne   
478855       2013-01-01            Ohio         Lorain   
478925       2013-01-05        Colorado         Aurora   
478959       2013-01-07  North Carolina     Greensboro   

                                               address  n_killed  n_injured  \
incident_id                                                                   
461105       1506 Versailles Avenue and Coursin Street         0          4   
460726                    13500 block of Cerise Avenue         1          3   
478855                           1776 East 28th Street         1          3   
478925                16000 block of East Ithaca Place         4          0   
478959                       307 Mourning Dove Terrace         2          2   

                                                  incident_url  \
incident_id                                                      
461105       http://www.gunviolencearchive.org/incident/461105   
460726       http://www.gunviolencearchive.org/incident/460726   
478855       http://www.gunviolencearchive.org/incident/478855   
478925       http://www.gunviolencearchive.org/incident/478925   
478959       http://www.gunviolencearchive.org/incident/478959   

                                                    source_url  \
incident_id                                                      
461105       http://www.post-gazette.com/local/south/2013/0...   
460726       http://www.dailybulletin.com/article/zz/201301...   
478855       http://chronicle.northcoastnow.com/2013/02/14/...   
478925       http://www.dailydemocrat.com/20130106/aurora-s...   
478959       http://www.journalnow.com/news/local/article_d...   

             incident_url_fields_missing  congressional_district  ...  \
incident_id                                                       ...   
461105                             False                    14.0  ...   
460726                             False                    43.0  ...   
478855                             False                     9.0  ...   
478925                             False                     6.0  ...   
478959                             False                     6.0  ...   

                               participant_age  \
incident_id                                      
461105                                   0::20   
460726                                   0::20   
478855       0::25||1::31||2::33||3::34||4::33   
478925              0::29||1::33||2::56||3::33   
478959              0::18||1::46||2::14||3::47   

                                         participant_age_group  \
incident_id                                                      
461105       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
460726       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
478855       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
478925       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
478959       0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...   

                                      participant_gender  \
incident_id                                                
461105              0::Male||1::Male||3::Male||4::Female   
460726                                           0::Male   
478855       0::Male||1::Male||2::Male||3::Male||4::Male   
478925              0::Female||1::Male||2::Male||3::Male   
478959            0::Female||1::Male||2::Male||3::Female   

                                              participant_name  \
incident_id                                                      
461105                                          0::Julian Sims   
460726                                       0::Bernard Gillis   
478855       0::Damien Bell||1::Desmen Noble||2::Herman Sea...   
478925       0::Stacie Philbrook||1::Christopher Ratlif

In [9]:
df_gun.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 239677 entries, 461105 to 1081940
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   date                         239677 non-null  object 
 1   state                        239677 non-null  object 
 2   city_or_county               239677 non-null  object 
 3   address                      223180 non-null  object 
 4   n_killed                     239677 non-null  int64  
 5   n_injured                    239677 non-null  int64  
 6   incident_url                 239677 non-null  object 
 7   source_url                   239209 non-null  object 
 8   incident_url_fields_missing  239677 non-null  bool   
 9   congressional_district       227733 non-null  float64
 10  gun_stolen                   140179 non-null  object 
 11  gun_type                     140226 non-null  object 
 12  incident_characteristics     239351 non-null  object

In [10]:
df_gun.shape

(239677, 28)

### 1.2.3 Import county education data set

In [11]:
df_edu = pd.read_csv(os.path.join(path, '2_Data', 'Raw Data', 'education.csv'))

In [12]:
df_edu.head()

FIPS Code State         Area name  2003 Rural-urban Continuum Code  \
0       1007    AL       Bibb County                              1.0   
1       1009    AL     Blount County                              1.0   
2       1021    AL    Chilton County                              1.0   
3       1073    AL  Jefferson County                              1.0   
4       1115    AL  St. Clair County                              1.0   

   2003 Urban Influence Code  2013 Rural-urban Continuum Code  \
0                        1.0                              1.0   
1                        1.0                              1.0   
2                        1.0                              1.0   
3                        1.0                              1.0   
4                        1.0                              1.0   

   2013 Urban Influence Code City/Suburb/Town/Rural 2013  \
0                        1.0                        City   
1                        1.0                        City   
2                        1.0                        City   
3                        1.0                        City   
4                        1.0                        City   

  Less than a high school diploma, 1970 High school diploma only, 1970  ...  \
0                                 5,272                          1,402  ...   
1                                10,677                          3,440  ...   
2                                10,285                          2,805  ...   
3                               186,882                        101,656  ...   
4                                10,304                          3,540  ...   

  Percent of adults completing some college or associate's degree, 2000  \
0                                               20.4                      
1                                               24.8                      
2                                               20.5                      
3                                               28.4                      
4                                               25.6                      

  Percent of adults with a bachelor's degree or higher, 2000  \
0                                                7.1           
1                                                9.6           
2                                                9.9           
3                                               24.6           
4                                               11.1           

   Less than a high school diploma, 2015-19  \
0                                     3,386   
1                                     7,763   
2                                     5,474   
3                                    44,684   
4                                     9,488   

   High school diploma only, 2015-19  \
0                              7,256   
1                             13,299   
2                             13,348   
3                            118,636   
4                             21,849   

   Some college or associate's degree, 2015-19  \
0                                        3,848   
1                                       13,519   
2                                        7,401   
3                                      136,299   
4                                       20,207   

   Bachelor's degree or higher, 2015-19  \
0                                 1,678   
1                                 5,210   
2                                 3,823   
3                               150,124   
4                                 9,880   

  Percent of adults with less than a high school diploma, 2015-19  \
0                                               20.9                
1                                               19.5                
2                                               18.2                
3                                                9.9                
4                                               15.4                

  

In [13]:
df_edu.shape

(3283, 48)

In [14]:
df_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3283 entries, 0 to 3282
Data columns (total 48 columns):
 #   Column                                                                    Non-Null Count  Dtype  
---  ------                                                                    --------------  -----  
 0   FIPS Code                                                                 3283 non-null   int64  
 1   State                                                                     3283 non-null   object 
 2   Area name                                                                 3283 non-null   object 
 3   2003 Rural-urban Continuum Code                                           3221 non-null   float64
 4   2003 Urban Influence Code                                                 3221 non-null   float64
 5   2013 Rural-urban Continuum Code                                           3221 non-null   float64
 6   2013 Urban Influence Code                                       

### 1.2.4 Import county unemployment data set

In [15]:
df_job = pd.read_csv(os.path.join(path, '2_Data', 'Raw Data', 'unemployment.csv'))

In [16]:
df_job.head()

FIPS_Code State             Area_name  Rural_urban_continuum_code_2013  \
0       1007    AL       Bibb County, AL                              1.0   
1       1009    AL     Blount County, AL                              1.0   
2       1021    AL    Chilton County, AL                              1.0   
3       1073    AL  Jefferson County, AL                              1.0   
4       1115    AL  St. Clair County, AL                              1.0   

   Urban_influence_code_2013 City/Suburb/Town/Rural  Metro_2013  \
0                        1.0                   City         1.0   
1                        1.0                   City         1.0   
2                        1.0                   City         1.0   
3                        1.0                   City         1.0   
4                        1.0                   City         1.0   

  Civilian_labor_force_2000 Employed_2000 Unemployed_2000  ...  \
0                     8,623         8,160             463  ...   
1                    25,266        24,375             891  ...   
2                    19,601        18,752             849  ...   
3                   331,141       317,868          13,273  ...   
4                    31,555        30,359           1,196  ...   

   Civilian_labor_force_2019 Employed_2019 Unemployed_2019  \
0                      8,639         8,371             268   
1                     25,196        24,516             680   
2                     19,841        19,296             545   
3                    316,802       307,648           9,154   
4                     40,698        39,591           1,107   

  Unemployment_rate_2019  Civilian_labor_force_2020 Employed_2020  \
0                    3.1                      8,640         8,067   
1                    2.7                     24,661        23,653   
2                    2.7                     19,592        18,618   
3                    2.9                    315,957       296,282   
4                    2.7                     40,132        38,146   

  Unemployed_2020 Unemployment_rate_2020  Median_Household_Income_2019  \
0             573                    6.6                        47,918   
1           1,008                    4.1                        52,902   
2             974                    5.0                        49,692   
3          19,675                    6.2                        54,127   
4           1,986                    4.9                        65,403   

  Med_HH_Income_Percent_of_State_Total_2019  
0                                      92.6  
1                                     102.2  
2                                      96.0  
3                                     104.6  
4                                     126.3  

[5 rows x 93 columns]

In [17]:
df_job.shape

(3275, 93)

In [18]:
df_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3275 entries, 0 to 3274
Data columns (total 93 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   FIPS_Code                                  3275 non-null   int64  
 1   State                                      3275 non-null   object 
 2   Area_name                                  3275 non-null   object 
 3   Rural_urban_continuum_code_2013            3219 non-null   float64
 4   Urban_influence_code_2013                  3219 non-null   float64
 5   City/Suburb/Town/Rural                     3219 non-null   object 
 6   Metro_2013                                 3222 non-null   float64
 7   Civilian_labor_force_2000                  3270 non-null   object 
 8   Employed_2000                              3270 non-null   object 
 9   Unemployed_2000                            3270 non-null   object 
 10  Unemployment_rate_2000  

# 2.0 Cleaning of the HUD dataset before exploratory analysis

## 2.1 Drop unnecessary columns from the dataset 

__Knowing that many of the 286 columns will not be needed for my planned analysis, I exported the 'HUD Multifamily Housing Asssisted Properties.csv' file into Excel to filter and explore. (If the dataset were too large to export into Excel I could have taken a sample in this Jupyter notebook and exported a sample .csv file that would have fit in Excel for exploratory analysis.) I was able to then decide on which columns I felt were useful for my project and which would be redundant. I then dropped all columns that were not needed.__

__In an initial exploration of the dataset in Python/ Jupyter and Excel, I quickly came to the conclusion that any analysis of the HUD data with other socio-economic data on housing rent, education, income, and/or crime would require common geographic identificaiton.  The HUD data using multiple geographic reference data including longitude and latitude, street address, city, state, ZIP code and FIPS (Federal Information Processing Standards) county codes; whereas the other datasets I identified to use in an analysis of housing rent, education, income, crime, etc. mainly used county names as a commone reference point. I found a dataset in Kaggle that matched ZIP and FIPS codes to County/ State names. This this I searched and found references to both ZIP and FIPS codes in the HUD data set. Having read the data limitations of the HUD data set, that there is the potential for errors, I decided to keep both codes to geolocate data points in the HUD data set to US counties as a way to triangulate results and eliminate potential errors.__

In [19]:
# Drop columns that are not relevant to the planned analysis comparing US Counties receiving multifamily assisted housing support with other socio-economic data
df_HUD.drop(columns=df_HUD.columns[194:], inplace=True)

In [20]:
df_HUD.drop(columns=df_HUD.columns[170:193], inplace=True)

In [21]:
df_HUD.drop(columns=df_HUD.columns[41:167], inplace=True)

In [22]:
df_HUD.drop(columns=df_HUD.columns[29:40], inplace=True)

In [23]:
df_HUD.drop(columns=df_HUD.columns[13:28], inplace=True)

In [24]:
df_HUD.drop(columns=df_HUD.columns[10:12], inplace=True)

In [25]:
df_HUD.drop(columns=df_HUD.columns[2:9], inplace=True)

In [26]:
# Check revised dataframe
df_HUD.head()

X          Y      ADDRESS_LINE1_TEXT  \
index                                                 
0     -83.094242  40.309009          560 Buehler Dr   
1     -86.143070  41.652389        900 Roosevelt Dr   
2     -76.601014  39.309478       1300 E LANVALE ST   
3     -86.347000  38.367692  521 SOUTH SUGAR STREET   
4     -87.703574  41.886009        271 N Albany Ave   

      CONGRESSIONAL_DISTRICT_CODE HAS_ACTIVE_FINANCING_IND TROUBLED_CODE  \
index                                                                      
0                              12                        Y             P   
1                              02                        N             N   
2                              07                        N             P   
3                              09                        N             N   
4                              07                        Y             P   

        STD_CITY STD_ST  STD_ZIP5  COUNTY_LEVEL  
index                                            
0       Delaware     OH   43015.0       39041.0  
1      Mishawaka     IN   46544.0       18141.0  
2      Baltimore     MD   21213.0       24510.0  
3        Marengo     IN   47140.0       18025.0  
4        Chicago     IL   60612.0       17031.0

## 2.2 Rename columns to aid understanding and analysis

__With the columns identified and decremented to those needed for the analysis the next step is to rename the columns for easier understanding and analysis__

In [27]:
df_HUD.rename({'X': 'Longitude', 'Y': 'Latitude', 'ADDRESS_LINE1_TEXT': 'STREET ADDRESS', 'CONGRESSIONAL_DISTRICT_CODE': 'CONGRESSIONAL DISTRICT CODE','HAS_ACTIVE_FINANCING_IND': 'HAS ACTIVE FINANCING', 'TROUBLED_CODE': 'TROUBLED CODE', 'STD_CITY': 'CITY', 'STD_ST': 'STATE', 'STD_ZIP5': 'ZIP CODE', 'COUNTY_LEVEL': 'COUNTY FIPS CODE'}, axis=1, inplace=True)

In [28]:
df_HUD.head()

Longitude   Latitude          STREET ADDRESS  \
index                                                 
0     -83.094242  40.309009          560 Buehler Dr   
1     -86.143070  41.652389        900 Roosevelt Dr   
2     -76.601014  39.309478       1300 E LANVALE ST   
3     -86.347000  38.367692  521 SOUTH SUGAR STREET   
4     -87.703574  41.886009        271 N Albany Ave   

      CONGRESSIONAL DISTRICT CODE HAS ACTIVE FINANCING TROUBLED CODE  \
index                                                                  
0                              12                    Y             P   
1                              02                    N             N   
2                              07                    N             P   
3                              09                    N             N   
4                              07                    Y             P   

            CITY STATE  ZIP CODE  COUNTY FIPS CODE  
index                                               
0       Delaware    OH   43015.0           39041.0  
1      Mishawaka    IN   46544.0           18141.0  
2      Baltimore    MD   21213.0           24510.0  
3        Marengo    IN   47140.0           18025.0  
4        Chicago    IL   60612.0           17031.0

## 2.3 Complete data consistency checks

In [29]:
df_HUD.describe()

Longitude      Latitude      ZIP CODE  COUNTY FIPS CODE
count  23601.000000  23601.000000  23601.000000      23601.000000
mean     -89.102291     38.584642  45364.140418      29494.996102
std       15.932989      5.253517  29073.125323      15556.358239
min     -162.111900     13.505100    601.000000       1001.000000
25%      -95.174906     35.225889  20872.000000      17097.000000
50%      -85.050534     39.735540  43812.000000      29157.000000
75%      -77.575290     41.964807  68104.000000      41051.000000
max      145.751125     66.657500  99901.000000      78030.000000

In [30]:
df_HUD.info

<bound method DataFrame.info of         Longitude   Latitude               STREET ADDRESS  \
index                                                       
0      -83.094242  40.309009               560 Buehler Dr   
1      -86.143070  41.652389             900 Roosevelt Dr   
2      -76.601014  39.309478            1300 E LANVALE ST   
3      -86.347000  38.367692       521 SOUTH SUGAR STREET   
4      -87.703574  41.886009             271 N Albany Ave   
...           ...        ...                          ...   
23629  -84.166541  31.585920        716 W. Society Avenue   
23630 -106.344182  31.794893            10200 Hedgerow Ct   
23631  -79.373419  34.420285  301 Martin Luther King Blvd   
23632  -72.309187  43.647435              16 Tracy Street   
23633  -95.210993  29.664566             1620 Spencer Hwy   

      CONGRESSIONAL DISTRICT CODE HAS ACTIVE FINANCING TROUBLED CODE  \
index                                                                  
0                             

__This shows the presence of some missing (NaN) data. Further, the count for Longitude, Latitude, ZIP, and FIPS code is 23,601 while the shape() function shows 23,634 rows. Each variable is to be checked for missing variables__

### 2.3.1 Identify missing values

In [31]:
# Check each variable for missing NaN values
df_HUD['Longitude'].value_counts(dropna = False)

 NaN           33
-66.034800     10
-66.596400      9
-83.327797      8
-112.013892     8
               ..
-95.604992      1
-92.980951      1
-92.455493      1
-93.304306      1
-95.210993      1
Name: Longitude, Length: 22800, dtype: int64

In [32]:
df_HUD['Latitude'].value_counts(dropna = False)

NaN          33
18.234200    10
18.074400     9
34.723850     8
34.575116     8
             ..
45.319422     1
45.050418     1
46.721535     1
47.317745     1
29.664566     1
Name: Latitude, Length: 22796, dtype: int64

In [33]:
df_HUD['STREET ADDRESS'].value_counts(dropna = False)

NaN                   32
910 E Broad St         6
496 Boulevard, NE      5
859 S 12th St          5
437 S Pond St          5
                      ..
805 WILDWOOD RD        1
810 CLOQUET AVE        1
116 SILVERWOOD AVE     1
410 MCKNIGHT RD S      1
1620 Spencer Hwy       1
Name: STREET ADDRESS, Length: 23280, dtype: int64

In [34]:
df_HUD['CONGRESSIONAL DISTRICT CODE'].value_counts(dropna = False)

01             3050
02             2577
03             2099
04             1770
05             1558
               ... 
1st               1
007               1
92                1
0912              1
AR-01 (115)       1
Name: CONGRESSIONAL DISTRICT CODE, Length: 108, dtype: int64

In [35]:
df_HUD['HAS ACTIVE FINANCING'].value_counts(dropna = False)

Y    12750
N    10884
Name: HAS ACTIVE FINANCING, dtype: int64

In [36]:
df_HUD['TROUBLED CODE'].value_counts(dropna = False)

N      15938
P       6159
T        824
NaN      713
Name: TROUBLED CODE, dtype: int64

__I had thought of using the 'TROUBLED CODE' as part of the analysis but with so many NaN values I will just drop the column in the next cleaning step__

In [37]:
df_HUD['CITY'].value_counts(dropna = False)

Chicago             317
Los Angeles         247
Brooklyn            189
New York            181
Philadelphia        169
                   ... 
Briarcliff Manor      1
Glens Falls           1
Guilderland           1
Endwell               1
West Lebanon          1
Name: CITY, Length: 5039, dtype: int64

In [38]:
df_HUD['STATE'].value_counts(dropna = False)

CA     1778
NY     1398
OH     1349
PA     1044
TX      990
IL      925
MA      902
NC      896
MI      707
MN      695
NJ      691
FL      685
WI      644
TN      593
GA      587
KY      497
IN      496
MO      496
MD      495
VA      478
WA      447
SC      406
AL      405
CT      397
MS      347
AR      347
CO      345
OR      332
LA      331
ME      292
KS      276
IA      266
OK      258
RI      243
NH      232
WV      225
NE      214
AZ      202
PR      198
SD      188
VT      151
NM      134
ID      133
DE      129
MT      119
ND      107
HI      105
UT      104
DC      102
AK       70
NV       67
WY       65
NaN      29
VI       17
MP        4
GU        1
Name: STATE, dtype: int64

In [39]:
df_HUD['ZIP CODE'].value_counts(dropna = False)

2119.0     34
60653.0    33
NaN        33
60637.0    32
2121.0     30
           ..
8045.0      1
11561.0     1
12883.0     1
12803.0     1
3784.0      1
Name: ZIP CODE, Length: 9128, dtype: int64

In [40]:
df_HUD['COUNTY FIPS CODE'].value_counts(dropna = False)

6037.0     628
17031.0    394
25025.0    259
42003.0    214
36047.0    186
          ... 
28037.0      1
18135.0      1
20043.0      1
20117.0      1
13111.0      1
Name: COUNTY FIPS CODE, Length: 2555, dtype: int64

In [41]:
df_HUD.isnull().sum()

Longitude                       33
Latitude                        33
STREET ADDRESS                  32
CONGRESSIONAL DISTRICT CODE    498
HAS ACTIVE FINANCING             0
TROUBLED CODE                  713
CITY                            29
STATE                           29
ZIP CODE                        33
COUNTY FIPS CODE                33
dtype: int64

__Longitude, Latitude, ZIP, and FIPS CODE show 33 NaN values, STREET ADDRESS has 32 NaN values, while CITY and STATE has 29 NaN vales.__ 

__Given the previously reported discrepancy of row count between Longitude, Latitude, ZIP CODE, and FIPS Code and shape() of 33 rows (23602 and 23634 respectively) it is possible that the NaN values might occur in the same rows and so limit the loss of data is they are removed from the analysis.  There is no appropriate method to impute the missing data, so the entries with missing data will be removed.__

__More concerning is that CONGRESSIONAL DISTRICT CODE amd TROUBLED CODE have 498 and 713 NaN values each. I had hoped to use these variables in the analysis, and while the loss of 713 entries only represents <5% of the sample, I have decided to drop these variables completely at this point. Should the exploratory data analysis show that incorporating these variables will add value to my project, I will go back to add them in with the missing data entries removed.__ 

In [42]:
# Remove the CONGRESSIONAL DISTRICT CODE and TROUBLED CODE variables
df_HUD.drop(columns = ['CONGRESSIONAL DISTRICT CODE'], inplace=True)
df_HUD.drop(columns = ['TROUBLED CODE'], inplace=True)

### 2.3.2 Remove entries with missing values

In [43]:
# Check which rows have missing values
df_HUD_nan = df_HUD[df_HUD['Longitude'].isnull() == True]

In [44]:
df_HUD_nan

Longitude  Latitude                       STREET ADDRESS  \
index                                                             
10196        NaN       NaN                   209 CORDOVA AVENUE   
17731        NaN       NaN  Urb. Las Leandras - Street #3 Final   
19660        NaN       NaN                 11430 Piedmont Drive   
22630        NaN       NaN                                  NaN   
22686        NaN       NaN                                  NaN   
22819        NaN       NaN                                  NaN   
22852        NaN       NaN                                  NaN   
22889        NaN       NaN                                  NaN   
22932        NaN       NaN                                  NaN   
22933        NaN       NaN                                  NaN   
22951        NaN       NaN         200 Block of N Woodington Rd   
22975        NaN       NaN                                  NaN   
23009        NaN       NaN                                  NaN   
23016        NaN       NaN                                  NaN   
23105        NaN       NaN                                  NaN   
23128        NaN       NaN                                  NaN   
23225        NaN       NaN                                  NaN   
23432        NaN       NaN                                  NaN   
23442        NaN       NaN                                  NaN   
23443        NaN       NaN                                  NaN   
23456        NaN       NaN                                  NaN   
23478        NaN       NaN                                  NaN   
23479        NaN       NaN                                  NaN   
23489        NaN       NaN                                  NaN   
23494        NaN       NaN                                  NaN   
23503        NaN       NaN                                  NaN   
23513        NaN       NaN                                  NaN   
23514        NaN       NaN                                  NaN   
23515        NaN       NaN                                  NaN   
23536        NaN       NaN                                  NaN   
23596        NaN       NaN                                  NaN   
23597        NaN       NaN                                  NaN   
23598        NaN       NaN                                  NaN   

      HAS ACTIVE FINANCING             CITY STATE  ZIP CODE  COUNTY FIPS CODE  
index                                                                          
10196                    Y  Egg Harbor City    NJ       NaN               NaN  
17731                    Y          Humacao    PR       NaN               NaN  
19660                    Y     Spotsylvania    VA       NaN               NaN  
22630                    N              NaN   NaN       NaN               NaN  
22686                    N              NaN   NaN       NaN               NaN  
22819                    N              NaN   NaN       NaN               NaN  
22852                    N              NaN   NaN       NaN               NaN  
22889                    N              NaN   NaN       NaN               NaN  
22932                    N              NaN   NaN       NaN               NaN  
22933                    N              NaN   NaN       NaN               NaN  
22951                    Y        Baltimore    MD       NaN               NaN  
22975                    N              NaN   NaN       NaN               NaN  
23009                    N              NaN   NaN       NaN               NaN  
23016                    N              NaN   NaN       NaN               NaN  
23105                    N              NaN   NaN       NaN               NaN  
23128                    N              NaN   NaN       NaN               NaN  
23225                    N              NaN   NaN       NaN               NaN  
23432                    N              NaN   NaN       NaN               NaN  
23442                    N              NaN   NaN       NaN  

   __This shows that all the NaN values for Longitude, Latitude, CITY, STATE, ZIP, and FIPS CODE are contained within the same rows.  There are 3 additional NaN values for STREET ADDRESS that aren't.__

In [45]:
df_HUD_nan2 = df_HUD[df_HUD['STREET ADDRESS'].isnull() == True]

In [46]:
df_HUD_nan2

Longitude  Latitude STREET ADDRESS HAS ACTIVE FINANCING        CITY  \
index                                                                        
22012   -91.9054   32.7796            NaN                    N     Bastrop   
22069   -75.5483   39.7466            NaN                    N  Wilmington   
22630        NaN       NaN            NaN                    N         NaN   
22686        NaN       NaN            NaN                    N         NaN   
22819        NaN       NaN            NaN                    N         NaN   
22852        NaN       NaN            NaN                    N         NaN   
22889        NaN       NaN            NaN                    N         NaN   
22932        NaN       NaN            NaN                    N         NaN   
22933        NaN       NaN            NaN                    N         NaN   
22975        NaN       NaN            NaN                    N         NaN   
23009        NaN       NaN            NaN                    N         NaN   
23016        NaN       NaN            NaN                    N         NaN   
23105        NaN       NaN            NaN                    N         NaN   
23128        NaN       NaN            NaN                    N         NaN   
23225        NaN       NaN            NaN                    N         NaN   
23391   -74.9096   39.8864            NaN                    N     Marlton   
23432        NaN       NaN            NaN                    N         NaN   
23442        NaN       NaN            NaN                    N         NaN   
23443        NaN       NaN            NaN                    N         NaN   
23456        NaN       NaN            NaN                    N         NaN   
23478        NaN       NaN            NaN                    N         NaN   
23479        NaN       NaN            NaN                    N         NaN   
23489        NaN       NaN            NaN                    N         NaN   
23494        NaN       NaN            NaN                    N         NaN   
23503        NaN       NaN            NaN                    N         NaN   
23513        NaN       NaN            NaN                    N         NaN   
23514        NaN       NaN            NaN                    N         NaN   
23515        NaN       NaN            NaN                    N         NaN   
23536        NaN       NaN            NaN                    N         NaN   
23596        NaN       NaN            NaN                    N         NaN   
23597        NaN       NaN            NaN                    N         NaN   
23598        NaN       NaN            NaN                    N         NaN   

      STATE  ZIP CODE  COUNTY FIPS CODE  
index                                    
22012    LA   71220.0           22067.0  
22069    DE   19801.0           10003.0  
22630   NaN       NaN               NaN  
22686   NaN       NaN               NaN  
22819   NaN       NaN               NaN  
22852   NaN       NaN               NaN  
22889   NaN       NaN               NaN  
22932   NaN       NaN               NaN  
22933   NaN       NaN               NaN  
22975   NaN       NaN               NaN  
23009   NaN       NaN               NaN  
23016   NaN       NaN               NaN  
23105   NaN       NaN               NaN  
23128   NaN       NaN               NaN  
23225   NaN       NaN               NaN  
23391    NJ    8053.0           34005.0  
23432   NaN       NaN               NaN  
23442   NaN       NaN               NaN  
23443   NaN       NaN               NaN  
23456   NaN       NaN               NaN  
23478   NaN       NaN               NaN  
23479   NaN       NaN               NaN  
23489   NaN       NaN               NaN  
23494   NaN       NaN               NaN  
23503   NaN       NaN               NaN  
23513   NaN       NaN               NaN  
23514   NaN       NaN               NaN  
23515   NaN       NaN               NaN  
23536   NaN       NaN               NaN  
23596   NaN       NaN               NaN  
23597   Na

__The additional missing values are in index # 22012, 22069, and 23391__

__In total 36 rows should be lost by removing all NaN value entries__

In [47]:
# Remove entries with missing NaN values
df_HUD.dropna(inplace = True)

In [48]:
# Check the shape of the cleaned dataframe 
df_HUD.shape

(23598, 8)

__This adds up as 23634 - 36 = 23598 rows__

In [49]:
# Recheck for any remaining missing values
df_HUD_nan3 = df_HUD[df_HUD['Latitude'].isnull() == True]

In [50]:
df_HUD_nan3

Empty DataFrame
Columns: [Longitude, Latitude, STREET ADDRESS, HAS ACTIVE FINANCING, CITY, STATE, ZIP CODE, COUNTY FIPS CODE]
Index: []

In [51]:
df_HUD_nan4 = df_HUD[df_HUD['STREET ADDRESS'].isnull() == True]

In [52]:
df_HUD_nan4

Empty DataFrame
Columns: [Longitude, Latitude, STREET ADDRESS, HAS ACTIVE FINANCING, CITY, STATE, ZIP CODE, COUNTY FIPS CODE]
Index: []

## 2.4 Check variable data types

In [53]:
# Confirm the variable type and other information of the cleaned dataframe
df_HUD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23598 entries, 0 to 23633
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Longitude             23598 non-null  float64
 1   Latitude              23598 non-null  float64
 2   STREET ADDRESS        23598 non-null  object 
 3   HAS ACTIVE FINANCING  23598 non-null  object 
 4   CITY                  23598 non-null  object 
 5   STATE                 23598 non-null  object 
 6   ZIP CODE              23598 non-null  float64
 7   COUNTY FIPS CODE      23598 non-null  float64
dtypes: float64(4), object(4)
memory usage: 1.6+ MB


In [54]:
# Check for mixed data types
for col in df_HUD.columns.tolist():
  weird = (df_HUD[[col]].applymap(type) != df_HUD[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_HUD[weird]) > 0:
    print (col)

__Variable data types are all ok, with no mixed data types__

## 2.5 Check for duplicate data entries

In [55]:
df_HUD_dups = df_HUD[df_HUD.duplicated()]

In [56]:
df_HUD_dups.head(50)

Longitude   Latitude                 STREET ADDRESS  \
index                                                         
222    -85.645032  31.418493           1525 MIXON SCHOOL RD   
324    -88.077861  30.597781      3577 Dauphin Island Pkwy.   
508   -112.013892  34.723850                  859 S 12th St   
670    -94.024074  33.400652                   2225 East St   
707   -112.013892  34.723850                  859 S 12th St   
1029  -122.430600  37.778216              40 Friendship Way   
1449  -121.440757  38.548038             701 FAIRGROUNDS DR   
1467  -121.440757  38.548038             701 FAIRGROUNDS DR   
1970  -117.708190  33.585354                25952 VIA LOMAS   
2038   -85.258330  30.777607         4052 OLD COTTONDALE RD   
2175  -122.324748  41.320395               1020 KINGSTON RD   
2326   -75.151406  38.763042           1142-306 SAVANNAH RD   
2528   -75.518864  39.167162                  430 KINGS HWY   
2529   -75.555132  39.743968             606 N Jefferson St   
2568   -75.518864  39.167162                  430 KINGS HWY   
2723   -72.873275  41.314414                 315 EASTERN ST   
2836  -103.721187  38.060086                  702 SANDIA DR   
2902   -72.941057  41.312201             392 ORCHARD STREET   
3310   -84.372091  33.767796              496 Boulevard, NE   
3317   -84.372091  33.767796              496 Boulevard, NE   
3319   -84.372091  33.767796              496 Boulevard, NE   
3375   -84.372091  33.767796              496 Boulevard, NE   
3518   -82.543821  27.477608         2511 16th St. Ct. East   
3668   -81.650806  26.599633                1291 BROAD ST W   
3705   -81.385463  28.551894               633 LAKE DOT CIR   
4186   -89.173870  37.004976                    310 18th St   
4307   -86.109186  39.648463                8102 REXMILL DR   
4308   -86.364116  39.606127              301 SPRINGMILL DR   
4441   -96.336590  42.478909                 5300 STONE AVE   
4593   -92.042652  42.170435                1603 W FIRST ST   
4774   -86.869185  41.692283                  3401 SALEM CT   
4840   -85.988279  39.820449           10202 John Jay Drive   
4915   -85.988279  39.820449              10202 JOHN JAY DR   
4926   -85.988279  39.820449              10202 JOHN JAY DR   
4928   -85.988279  39.820449           10202 John Jay Drive   
4929   -85.103535  39.638706          1889 E. State Road 44   
4939   -85.988279  39.820449           10202 John Jay Drive   
4968   -86.240130  39.719769         4562 WEST PERRY STREET   
5087   -87.035715  41.495509             2810 Winchester Dr   
5114   -86.041854  39.887686     7355 SHADELAND STATION WAY   
5216   -87.486093  37.985144               5300 CARRIAGE DR   
5248   -86.843953  40.396922               2511 MALDEN ROAD   
5303   -85.863390  39.222918  5135 N. LINCOLN VILLAGE DRIVE   
5314   -85.863390  39.222918  5135 N. LINCOLN VILLAGE DRIVE   
5337   -86.106601  39.740538                3520 CALHOUN ST   
5347   -86.106601  39.740538                3520 CALHOUN ST   
5351   -85.863390  39.222918  5135 N. LINCOLN VILLAGE DRIVE   
5375   -85.169193  40.752288                    58 Capri Ct   
5566   -91.565199  31.624563                    200 Kyle Rd   
5625   -71.810806  42.289014                   485 GROVE ST   

      HAS ACTIVE FINANCING           CITY STATE  ZIP CODE  COUNTY FIPS CODE  
index                                                                        
222                      N          Ozark    AL   36360.0            1045.0  
324                      N         Mobile    AL   36605.0            1097.0  
508                      Y     Cottonwood    AZ   86326.0            4025.0  
670                      Y      Texarkana    AR   71854.0            5091.0  
707                      Y     Cottonwood    AZ   86326.0            4025.0  
1029                     Y  San Francisco    CA   94117.0            6075.0  
1449                     N     Sacramento    CA   95817.0            6067.0  
1467                     N   

__Checking the duplicates on Excel, it is possible to see that these are not duplicate entries.  Although they share the same street address they represent different buildings containing multifamily housing units. Variables that would have distinguished them, such as 'Property_ID' were removed as not needed for the analysis. It is a good reminder to conduct duplicate checks before making revisions to data sets as part of data cleaning when possible.__

# 3.0 Cleaning of the Gun Violence dataset before exploratory analysis

## 3.1 Drop unnecessary columns from the dataset

__A review of the dataset using the info() function and after importing the .csv file into Excel was used to determine which variables were not necessary for this project's analysis__

In [57]:
# Drop variables that are not required
df_gun.drop(columns = 'notes', inplace=True)
df_gun.drop(columns = 'n_guns_involved', inplace=True)
df_gun.drop(columns = 'participant_age', inplace=True)

In [58]:
df_gun.drop(columns = 'participant_age_group', inplace=True)
df_gun.drop(columns = 'participant_gender', inplace=True)
df_gun.drop(columns = 'participant_name', inplace=True)

In [59]:
df_gun.drop(columns = 'participant_relationship', inplace=True)
df_gun.drop(columns = 'participant_status', inplace=True)
df_gun.drop(columns = 'participant_type', inplace=True)

In [60]:
df_gun.drop(columns = 'sources', inplace=True)
df_gun.drop(columns = 'gun_stolen', inplace=True)
df_gun.drop(columns = 'gun_type', inplace=True)

In [61]:
df_gun.drop(columns = 'incident_characteristics', inplace=True)
df_gun.drop(columns = 'location_description', inplace=True)
df_gun.drop(columns = 'n_killed', inplace=True)

In [62]:
df_gun.drop(columns = 'n_injured', inplace=True)
df_gun.drop(columns = 'incident_url', inplace=True)
df_gun.drop(columns = 'source_url', inplace=True)
df_gun.drop(columns = 'incident_url_fields_missing', inplace=True)

In [63]:
# Check the revised dataset
df_gun.head()

date           state city_or_county  \
incident_id                                              
461105       2013-01-01    Pennsylvania     Mckeesport   
460726       2013-01-01      California      Hawthorne   
478855       2013-01-01            Ohio         Lorain   
478925       2013-01-05        Colorado         Aurora   
478959       2013-01-07  North Carolina     Greensboro   

                                               address  \
incident_id                                              
461105       1506 Versailles Avenue and Coursin Street   
460726                    13500 block of Cerise Avenue   
478855                           1776 East 28th Street   
478925                16000 block of East Ithaca Place   
478959                       307 Mourning Dove Terrace   

             congressional_district  latitude  longitude  \
incident_id                                                
461105                         14.0   40.3467   -79.8559   
460726                         43.0   33.9090  -118.3330   
478855                          9.0   41.4455   -82.1377   
478925                          6.0   39.6518  -104.8020   
478959                          6.0   36.1140   -79.9569   

             state_house_district  state_senate_district  
incident_id                                               
461105                        NaN                    NaN  
460726                       62.0                   35.0  
478855                       56.0                   13.0  
478925                       40.0                   28.0  
478959                       62.0                   27.0

In [64]:
df_gun.shape

(239677, 9)

## 3.2 Complete data consistency checks

In [65]:
df_gun.describe()

congressional_district       latitude      longitude  \
count           227733.000000  231754.000000  231754.000000   
mean                 8.001265      37.546598     -89.338348   
std                  8.480835       5.130763      14.359546   
min                  0.000000      19.111400    -171.429000   
25%                  2.000000      33.903400     -94.158725   
50%                  5.000000      38.570600     -86.249600   
75%                 10.000000      41.437375     -80.048625   
max                 53.000000      71.336800      97.433100   

       state_house_district  state_senate_district  
count         200905.000000           207342.00000  
mean              55.447132               20.47711  
std               42.048117               14.20456  
min                1.000000                1.00000  
25%               21.000000                9.00000  
50%               47.000000               19.00000  
75%               84.000000               30.00000  
max              901.000000               94.00000

### 3.2.1 Check for missing/ NaN data values

In [66]:
df_gun.isnull().sum()

date                          0
state                         0
city_or_county                0
address                   16497
congressional_district    11944
latitude                   7923
longitude                  7923
state_house_district      38772
state_senate_district     32335
dtype: int64

__Of the variables with missing/ NaN values, the 'longitude' and 'latitude' are the most important to match up with the other data sets, and given the missing values for them >5% of the total sample, I can ignore and remove the 'address', 'congressional_district', 'state_house_district', and state_senate_district' variables.__

__The missing values for 'longitude' and latitude' represent 3% of the total sample - provided that the entry for each is missg in the same rows - so I will check, and if so, remove the NaN values without significantly affecting the overall analysis'__

In [67]:
# Remove the four variables with too many NaN values
df_gun.drop(columns = 'address', inplace=True)
df_gun.drop(columns = 'congressional_district', inplace=True)
df_gun.drop(columns = 'state_house_district', inplace=True)
df_gun.drop(columns = 'state_senate_district', inplace=True)

In [68]:
# Check that the missing data for 'longitude' and 'latitude' overlaps
df_gun_nan = df_gun[df_gun['longitude'].isnull() == True]

In [69]:
df_gun_nan.head(50)

date           state              city_or_county  latitude  \
incident_id                                                                     
972570       2013-12-01    Pennsylvania                       Derry       NaN   
935147       2013-12-31      California                     Oakland       NaN   
225046       2014-01-13           Texas                 San Antonio       NaN   
102368       2014-01-13        Virginia              Henrico County       NaN   
96780        2014-01-14        Delaware                   Millsboro       NaN   
97209        2014-01-15        Nebraska                       Omaha       NaN   
339227       2014-01-16      Washington                     Spokane       NaN   
671396       2014-01-17        Illinois                     Chicago       NaN   
98216        2014-01-18        New York                       Utica       NaN   
98261        2014-01-19        Illinois                 Bensenville       NaN   
283248       2014-01-23        Illinois                     Chicago       NaN   
102854       2014-02-01       Louisiana            Jefferson Parish       NaN   
1000666      2014-02-07  North Carolina                Fayetteville       NaN   
105496       2014-02-09        New York             Corona (Queens)       NaN   
107017       2014-02-12           Texas                 Brownsville       NaN   
107954       2014-02-18         Indiana                Indianapolis       NaN   
164024       2014-02-19        Illinois                       Alton       NaN   
108598       2014-02-20      California                     Oakland       NaN   
109423       2014-02-22      California                     Oakland       NaN   
353797       2014-02-23           Texas              Corpus Christi       NaN   
118616       2014-02-24  North Carolina               Maggie Valley       NaN   
112246       2014-03-05        Michigan                       Flint       NaN   
805960       2014-03-05     Connecticut                  Bridgeport       NaN   
112597       2014-03-06      California                 Los Angeles       NaN   
114977       2014-03-11           Texas               Missouri City       NaN   
114983       2014-03-14        Maryland                   Baltimore       NaN   
115811       2014-03-16        Illinois                    Danville       NaN   
116456       2014-03-18      New Jersey                      Newark       NaN   
116507       2014-03-19            Utah                 Toquerville       NaN   
116491       2014-03-19        Maryland  Curtis Bay (Orchard Beach)       NaN   
116916       2014-03-20      California                     Anaheim       NaN   
117301       2014-03-21      California                     Tarzana       NaN   
627538       2014-03-22           Texas                     El Paso       NaN   
935212       2014-03-25      California                     Oakland       NaN   
118825       2014-03-26       Louisiana                 New Orleans       NaN   
121747       2014-04-01           Texas                      Dallas       NaN   
124022       2014-04-08      Washington                   Arlington       NaN   
123671       2014-04-09   Massachusetts                     Holyoke       NaN   
124337       2014-04-11        Illinois                     Chicago       NaN   
699323       2014-04-12        Illinois                     Chicago       NaN   
125229       2014-04-14        New York                    Brooklyn       NaN   
125774       2014-04-16      California                     Oakland       NaN   
127192       2014-04-19      New Jersey                     Trenton       NaN   
128243       2014-04-20           Texas                 San Antonio       NaN   
128374       2014-04-21      California                     Oakland       NaN   
128876       2014-04-23           Texas                     Lubbock       NaN   
129020       2014-04-24      California                     Visalia       NaN   
129440       2014-04-25         Vermont           

In [70]:
df_gun_nan.head(50)

date           state              city_or_county  latitude  \
incident_id                                                                     
972570       2013-12-01    Pennsylvania                       Derry       NaN   
935147       2013-12-31      California                     Oakland       NaN   
225046       2014-01-13           Texas                 San Antonio       NaN   
102368       2014-01-13        Virginia              Henrico County       NaN   
96780        2014-01-14        Delaware                   Millsboro       NaN   
97209        2014-01-15        Nebraska                       Omaha       NaN   
339227       2014-01-16      Washington                     Spokane       NaN   
671396       2014-01-17        Illinois                     Chicago       NaN   
98216        2014-01-18        New York                       Utica       NaN   
98261        2014-01-19        Illinois                 Bensenville       NaN   
283248       2014-01-23        Illinois                     Chicago       NaN   
102854       2014-02-01       Louisiana            Jefferson Parish       NaN   
1000666      2014-02-07  North Carolina                Fayetteville       NaN   
105496       2014-02-09        New York             Corona (Queens)       NaN   
107017       2014-02-12           Texas                 Brownsville       NaN   
107954       2014-02-18         Indiana                Indianapolis       NaN   
164024       2014-02-19        Illinois                       Alton       NaN   
108598       2014-02-20      California                     Oakland       NaN   
109423       2014-02-22      California                     Oakland       NaN   
353797       2014-02-23           Texas              Corpus Christi       NaN   
118616       2014-02-24  North Carolina               Maggie Valley       NaN   
112246       2014-03-05        Michigan                       Flint       NaN   
805960       2014-03-05     Connecticut                  Bridgeport       NaN   
112597       2014-03-06      California                 Los Angeles       NaN   
114977       2014-03-11           Texas               Missouri City       NaN   
114983       2014-03-14        Maryland                   Baltimore       NaN   
115811       2014-03-16        Illinois                    Danville       NaN   
116456       2014-03-18      New Jersey                      Newark       NaN   
116507       2014-03-19            Utah                 Toquerville       NaN   
116491       2014-03-19        Maryland  Curtis Bay (Orchard Beach)       NaN   
116916       2014-03-20      California                     Anaheim       NaN   
117301       2014-03-21      California                     Tarzana       NaN   
627538       2014-03-22           Texas                     El Paso       NaN   
935212       2014-03-25      California                     Oakland       NaN   
118825       2014-03-26       Louisiana                 New Orleans       NaN   
121747       2014-04-01           Texas                      Dallas       NaN   
124022       2014-04-08      Washington                   Arlington       NaN   
123671       2014-04-09   Massachusetts                     Holyoke       NaN   
124337       2014-04-11        Illinois                     Chicago       NaN   
699323       2014-04-12        Illinois                     Chicago       NaN   
125229       2014-04-14        New York                    Brooklyn       NaN   
125774       2014-04-16      California                     Oakland       NaN   
127192       2014-04-19      New Jersey                     Trenton       NaN   
128243       2014-04-20           Texas                 San Antonio       NaN   
128374       2014-04-21      California                     Oakland       NaN   
128876       2014-04-23           Texas                     Lubbock       NaN   
129020       2014-04-24      California                     Visalia       NaN   
129440       2014-04-25         Vermont           

__The missing values for 'longitude' and 'latitude' appears to overlap, so I can remove all missing values and then I can view the shape of the dataframe to double check that this was ok to do.__

### 3.2.2 Drop missing/ NaN values

In [71]:
# Remove the NaN values from 'longitude' and 'latitude'
df_gun.dropna(inplace = True)

In [72]:
df_gun.shape

(231754, 5)

__The shape confirms that 7,923 rows were lost with deleting the missing values - so all missing values for 'longitude' and 'latitude' did match rows exactly.__

In [73]:
# Check the revised data set
df_gun.head()

date           state city_or_county  latitude  longitude
incident_id                                                                
461105       2013-01-01    Pennsylvania     Mckeesport   40.3467   -79.8559
460726       2013-01-01      California      Hawthorne   33.9090  -118.3330
478855       2013-01-01            Ohio         Lorain   41.4455   -82.1377
478925       2013-01-05        Colorado         Aurora   39.6518  -104.8020
478959       2013-01-07  North Carolina     Greensboro   36.1140   -79.9569

In [74]:
df_gun.tail()

date       state            city_or_county  latitude  \
incident_id                                                               
1082061      2018-03-31  Washington  Spokane (Spokane Valley)   47.6638   
1083139      2018-03-31   Louisiana              Natchitoches   31.7537   
1083151      2018-03-31   Louisiana                    Gretna   29.9239   
1082514      2018-03-31       Texas                   Houston   29.7201   
1081940      2018-03-31       Maine              Norridgewock   44.7293   

             longitude  
incident_id             
1082061      -117.2350  
1083139       -93.0836  
1083151       -90.0442  
1082514       -95.6110  
1081940       -69.7691

In [75]:
df_gun.isnull().sum()

date              0
state             0
city_or_county    0
latitude          0
longitude         0
dtype: int64

### 3.2.3 Check variable data types

In [76]:
df_gun.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 231754 entries, 461105 to 1081940
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   date            231754 non-null  object 
 1   state           231754 non-null  object 
 2   city_or_county  231754 non-null  object 
 3   latitude        231754 non-null  float64
 4   longitude       231754 non-null  float64
dtypes: float64(2), object(3)
memory usage: 10.6+ MB


In [77]:
# Check for mixed data types
for col in df_gun.columns.tolist():
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_gun[weird]) > 0:
    print (col)

## 3.3 Check for duplicates

In [78]:
df_gun_dups = df_gun[df_gun.duplicated()]

In [79]:
df_gun_dups

date       state city_or_county  latitude  longitude
incident_id                                                            
92736        2014-01-01       Texas        Lubbock   33.5922  -101.8180
100729       2014-01-01     Florida        Orlando   28.5064   -81.1511
217093       2014-01-02       Texas         Austin   30.2093   -97.6529
92830        2014-01-03   Louisiana    New Orleans   29.9551   -90.0747
92901        2014-01-03    Arkansas    Little Rock   34.7256   -92.3089
...                 ...         ...            ...       ...        ...
1073437      2018-03-19  California         Fresno   36.7387  -119.7900
1073444      2018-03-19  California         Fresno   36.7387  -119.7900
1073433      2018-03-19  California         Fresno   36.7387  -119.7900
1079685      2018-03-23  California      La Mirada   33.9034  -118.0170
1082422      2018-03-30    Illinois        Chicago   41.8753   -87.7428

[1486 rows x 5 columns]

__Unfortunately, while these look like duplicates the reality is that they are not.  They are in fact cases of multiple gun-crime incidents in the same ciy on the same day. The incident_id is different for each, recording a different incident, and other variables that would have distinguished the incidents was removed earlier in the data cleaning as it wasn't needed for the analysis.__

# 4.0 Cleaning of the Education dataset before exploratory analysis

## 4.1 Drop unneccesary columns

In [80]:
# Drop variable columns that are not needed for the analysis
df_edu.drop(columns = '2003 Rural-urban Continuum Code', inplace=True)
df_edu.drop(columns = '2003 Urban Influence Code', inplace=True)
df_edu.drop(columns = '2013 Rural-urban Continuum Code', inplace=True)
df_edu.drop(columns = '2013 Urban Influence Code', inplace=True)
df_edu.drop(columns = 'City/Suburb/Town/Rural 2013', inplace=True)

In [81]:
# Drop variable columns with absolute education outcomes as only the relative results are useful
df_edu.drop(columns = 'Less than a high school diploma, 1970', inplace=True)
df_edu.drop(columns = 'High school diploma only, 1970', inplace=True)
df_edu.drop(columns = 'Some college (1-3 years), 1970', inplace=True)
df_edu.drop(columns = 'Four years of college or higher, 1970', inplace=True)

In [82]:
df_edu.drop(columns = 'Less than a high school diploma, 1980', inplace=True)
df_edu.drop(columns = 'High school diploma only, 1980', inplace=True)
df_edu.drop(columns = 'Some college (1-3 years), 1980', inplace=True)
df_edu.drop(columns = 'Four years of college or higher, 1980', inplace=True)

In [83]:
df_edu.drop(columns = 'Less than a high school diploma, 1990', inplace=True)
df_edu.drop(columns = 'High school diploma only, 1990', inplace=True)
df_edu.drop(columns = "Some college or associate's degree, 1990", inplace=True)
df_edu.drop(columns = "Bachelor's degree or higher, 1990", inplace=True)

In [84]:
df_edu.drop(columns = 'Less than a high school diploma, 2000', inplace=True)
df_edu.drop(columns = 'High school diploma only, 2000', inplace=True)
df_edu.drop(columns = "Some college or associate's degree, 2000", inplace=True)
df_edu.drop(columns = "Bachelor's degree or higher, 2000", inplace=True)

In [85]:
df_edu.drop(columns = 'Less than a high school diploma, 2015-19', inplace=True)
df_edu.drop(columns = 'High school diploma only, 2015-19', inplace=True)
df_edu.drop(columns = "Some college or associate's degree, 2015-19", inplace=True)
df_edu.drop(columns = "Bachelor's degree or higher, 2015-19", inplace=True)

In [86]:
# Drop variable columns that are considered too old to include in the analysis
df_edu.drop(columns = 'Percent of adults with less than a high school diploma, 1970', inplace=True)
df_edu.drop(columns = 'Percent of adults with a high school diploma only, 1970', inplace=True)
df_edu.drop(columns = 'Percent of adults completing some college (1-3 years), 1970', inplace=True)
df_edu.drop(columns = 'Percent of adults completing four years of college or higher, 1970', inplace=True)

In [87]:
# Check revised data set
df_edu.head()

FIPS Code State         Area name  \
0       1007    AL       Bibb County   
1       1009    AL     Blount County   
2       1021    AL    Chilton County   
3       1073    AL  Jefferson County   
4       1115    AL  St. Clair County   

   Percent of adults with less than a high school diploma, 1980  \
0                                               59.5              
1                                               53.9              
2                                               54.0              
3                                               35.3              
4                                               50.1              

   Percent of adults with a high school diploma only, 1980  \
0                                               29.6         
1                                               32.4         
2                                               31.1         
3                                               33.1         
4                                               33.6         

   Percent of adults completing some college (1-3 years), 1980  \
0                                                6.1             
1                                                8.4             
2                                                8.5             
3                                               15.8             
4                                                9.9             

   Percent of adults completing four years of college or higher, 1980  \
0                                                4.9                    
1                                                5.3                    
2                                                6.5                    
3                                               15.8                    
4                                                6.4                    

   Percent of adults with less than a high school diploma, 1990  \
0                                               48.2              
1                                               39.5              
2                                               43.4              
3                                               26.2              
4                                               39.0              

   Percent of adults with a high school diploma only, 1990  \
0                                               33.8         
1                                               34.7         
2                                               32.6         
3                                               28.3         
4                                               32.9         

   Percent of adults completing some college or associate's degree, 1990  \
0                                               13.2                       
1                                               18.8                       
2                                               16.5                       
3                                               25.7                       
4                                               19.6                       

   Percent of adults with a bachelor's degree or higher, 1990  \
0                                                4.7            
1                                                7.0            
2                                                7.5            
3                                               19.9            
4                                                8.5            

   Percent of adults with less than a high school diploma, 2000  \
0                                               36.8              
1                                               29.6              
2                                               33.8              
3                                               19.1              
4                                               28.7              

   Percent of adults with a high school diploma only, 2000  \
0                                               35.7         

In [88]:
df_edu.shape

(3283, 19)

## 4.2 Data Consistency Checks

In [89]:
df_edu.describe()

FIPS Code  \
count   3283.000000   
mean   31308.242766   
std    16343.477485   
min        0.000000   
25%    19016.000000   
50%    30017.000000   
75%    46100.000000   
max    72153.000000   

       Percent of adults with less than a high school diploma, 1980  \
count                                        3267.000000              
mean                                           41.178114              
std                                            12.997850              
min                                             4.700000              
25%                                            31.700000              
50%                                            39.200000              
75%                                            51.400000              
max                                            82.400000              

       Percent of adults with a high school diploma only, 1980  \
count                                        3267.000000         
mean                                           34.356872         
std                                             7.537762         
min                                            11.000000         
25%                                            28.700000         
50%                                            35.000000         
75%                                            40.200000         
max                                            54.300000         

       Percent of adults completing some college (1-3 years), 1980  \
count                                        3267.000000             
mean                                           13.034619             
std                                             4.657774             
min                                             3.200000             
25%                                             9.500000             
50%                                            12.500000             
75%                                            16.100000             
max                                            32.000000             

       Percent of adults completing four years of college or higher, 1980  \
count                                        3267.000000                    
mean                                           11.432323                    
std                                             5.489187                    
min                                             1.600000                    
25%                                             7.900000                    
50%                                            10.000000                    
75%                                            13.500000                    
max                                            47.800000                    

       Percent of adults with less than a high school diploma, 1990  \
count                                        3271.000000              
mean                                           30.887955              
std                                            11.023930              
min                                             0.000000              
25%                                            22.800000              
50%                                            28.800000              
75%                                            38.850000              
max                                            73.100000              

       Percent of adults with a high school diploma only, 1990  \
count                                        3271.000000         
mean                                           33.886854         
std                                             6.414239         
min                                             0.000000         
25%                                            29.900000         
50%                                            33.500000         
75%                                            38.300000         
max                                            52.600000         

       

### 4.2.1 Identify missing/ NaN data

In [90]:
df_edu.isnull().sum()

FIPS Code                                                                    0
State                                                                        0
Area name                                                                    0
Percent of adults with less than a high school diploma, 1980                16
Percent of adults with a high school diploma only, 1980                     16
Percent of adults completing some college (1-3 years), 1980                 16
Percent of adults completing four years of college or higher, 1980          16
Percent of adults with less than a high school diploma, 1990                12
Percent of adults with a high school diploma only, 1990                     12
Percent of adults completing some college or associate's degree, 1990       13
Percent of adults with a bachelor's degree or higher, 1990                  12
Percent of adults with less than a high school diploma, 2000                11
Percent of adults with a high school diploma only, 2

In [91]:
# Check for any overlap of variables with missing data between rows
df_edu_nan = df_edu[df_edu['Percent of adults with less than a high school diploma, 1980'].isnull() == True]

In [92]:
df_edu_nan

FIPS Code State                          Area name  \
28         8014    CO                  Broomfield County   
1372       4012    AZ                      La Paz County   
1637      35006    NM                      Cibola County   
2108       2068    AK                     Denali Borough   
2726       2105    AK          Hoonah-Angoon Census Area   
2727       2198    AK  Prince of Wales-Hyder Census Area   
2917       2016    AK         Aleutians West Census Area   
2924       2195    AK             Petersburg Census Area   
3037       2013    AK             Aleutians East Borough   
3042       2164    AK         Lake and Peninsula Borough   
3043       2230    AK               Skagway Municipality   
3045       2275    AK          Wrangell City and Borough   
3046       2282    AK           Yakutat City and Borough   
3225       2160    AK                 Kuskokwim Division   
3228       2232    AK  Skagway-Hoonah-Angoon Census Area   
3229       2250    AK               Upper Yukon Division   

      Percent of adults with less than a high school diploma, 1980  \
28                                                  NaN              
1372                                                NaN              
1637                                                NaN              
2108                                                NaN              
2726                                                NaN              
2727                                                NaN              
2917                                                NaN              
2924                                                NaN              
3037                                                NaN              
3042                                                NaN              
3043                                                NaN              
3045                                                NaN              
3046                                                NaN              
3225                                                NaN              
3228                                                NaN              
3229                                                NaN              

      Percent of adults with a high school diploma only, 1980  \
28                                                  NaN         
1372                                                NaN         
1637                                                NaN         
2108                                                NaN         
2726                                                NaN         
2727                                                NaN         
2917                                                NaN         
2924                                                NaN         
3037                                                NaN         
3042                                                NaN         
3043                                                NaN         
3045                                                NaN         
3046                                                NaN         
3225                                                NaN         
3228                                                NaN         
3229                                                NaN         

      Percent of adults completing some college (1-3 years), 1980  \
28                                                  NaN             
1372                                                NaN             
1637                                                NaN             
2108                                                NaN             
2726                                                NaN             
2727                                                NaN             
2917                                                NaN             
2924                                                NaN             
3037                                                NaN            

__There is some overlap of variable missing/ NaN values across rows so the total possible missing/ NaN values represents <1.5% of the total data set. Therefore, I will delete all missing/ NaN data before conducting the analysis. As the time between data points is 10 years it is not possible to reliably impute missing values with any accuracy.__

### 4.2.2 Remove any missing/ NaN data

In [93]:
# Delete missing/ NaN values
df_edu.dropna(inplace = True)

In [94]:
# Check for any remaining missing data and the shape of the revised data set
df_edu.isnull().sum()

FIPS Code                                                                   0
State                                                                       0
Area name                                                                   0
Percent of adults with less than a high school diploma, 1980                0
Percent of adults with a high school diploma only, 1980                     0
Percent of adults completing some college (1-3 years), 1980                 0
Percent of adults completing four years of college or higher, 1980          0
Percent of adults with less than a high school diploma, 1990                0
Percent of adults with a high school diploma only, 1990                     0
Percent of adults completing some college or associate's degree, 1990       0
Percent of adults with a bachelor's degree or higher, 1990                  0
Percent of adults with less than a high school diploma, 2000                0
Percent of adults with a high school diploma only, 2000         

In [95]:
df_edu.shape

(3260, 19)

### 4.2.3 Check variable data types

In [96]:
df_edu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3260 entries, 0 to 3282
Data columns (total 19 columns):
 #   Column                                                                    Non-Null Count  Dtype  
---  ------                                                                    --------------  -----  
 0   FIPS Code                                                                 3260 non-null   int64  
 1   State                                                                     3260 non-null   object 
 2   Area name                                                                 3260 non-null   object 
 3   Percent of adults with less than a high school diploma, 1980              3260 non-null   float64
 4   Percent of adults with a high school diploma only, 1980                   3260 non-null   float64
 5   Percent of adults completing some college (1-3 years), 1980               3260 non-null   float64
 6   Percent of adults completing four years of college or higher, 19

In [97]:
# Check for mixed data types
for col in df_edu.columns.tolist():
  weird = (df_edu[[col]].applymap(type) != df_edu[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_edu[weird]) > 0:
    print (col)

## 4.3 Check for duplicates

In [98]:
df_edu_dups = df_edu[df_edu.duplicated()]

In [99]:
df_edu_dups

Empty DataFrame
Columns: [FIPS Code, State, Area name, Percent of adults with less than a high school diploma, 1980, Percent of adults with a high school diploma only, 1980, Percent of adults completing some college (1-3 years), 1980, Percent of adults completing four years of college or higher, 1980, Percent of adults with less than a high school diploma, 1990, Percent of adults with a high school diploma only, 1990, Percent of adults completing some college or associate's degree, 1990, Percent of adults with a bachelor's degree or higher, 1990, Percent of adults with less than a high school diploma, 2000, Percent of adults with a high school diploma only, 2000, Percent of adults completing some college or associate's degree, 2000, Percent of adults with a bachelor's degree or higher, 2000, Percent of adults with less than a high school diploma, 2015-19, Percent of adults with a high school diploma only, 2015-19, Percent of adults completing some college or associate's degree, 2015-19, Percent of adults with a bachelor's degree or higher, 2015-19]
Index: []

# 5.0 Cleaning of the Unemployment dataset before exploratory analysis

## 5.1 Drop any variable columns that are not necessary for the analysis

In [100]:
# Drop irrelevant columns
df_job.drop(columns = 'Rural_urban_continuum_code_2013', inplace=True)
df_job.drop(columns = 'Urban_influence_code_2013', inplace=True)
df_job.drop(columns = 'City/Suburb/Town/Rural', inplace=True)
df_job.drop(columns = 'Metro_2013', inplace=True)

In [101]:
# Drop variables with absolute employment figures and keep percentage rates only for comparison
df_job.drop(columns = 'Civilian_labor_force_2000', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2001', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2002', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2003', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2004', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2005', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2006', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2007', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2008', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2009', inplace=True)

In [102]:
df_job.drop(columns = 'Civilian_labor_force_2010', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2011', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2012', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2013', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2014', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2015', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2016', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2017', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2018', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2019', inplace=True)
df_job.drop(columns = 'Civilian_labor_force_2020', inplace=True)

In [103]:
df_job.drop(columns = 'Employed_2000', inplace=True)
df_job.drop(columns = 'Employed_2001', inplace=True)
df_job.drop(columns = 'Employed_2002', inplace=True)
df_job.drop(columns = 'Employed_2003', inplace=True)
df_job.drop(columns = 'Employed_2004', inplace=True)
df_job.drop(columns = 'Employed_2005', inplace=True)
df_job.drop(columns = 'Employed_2006', inplace=True)
df_job.drop(columns = 'Employed_2007', inplace=True)
df_job.drop(columns = 'Employed_2008', inplace=True)
df_job.drop(columns = 'Employed_2009', inplace=True)

In [104]:
df_job.drop(columns = 'Employed_2010', inplace=True)
df_job.drop(columns = 'Employed_2011', inplace=True)
df_job.drop(columns = 'Employed_2012', inplace=True)
df_job.drop(columns = 'Employed_2013', inplace=True)
df_job.drop(columns = 'Employed_2014', inplace=True)
df_job.drop(columns = 'Employed_2015', inplace=True)
df_job.drop(columns = 'Employed_2016', inplace=True)
df_job.drop(columns = 'Employed_2017', inplace=True)
df_job.drop(columns = 'Employed_2018', inplace=True)
df_job.drop(columns = 'Employed_2019', inplace=True)
df_job.drop(columns = 'Employed_2020', inplace=True)

In [105]:
df_job.drop(columns = 'Unemployed_2000', inplace=True)
df_job.drop(columns = 'Unemployed_2001', inplace=True)
df_job.drop(columns = 'Unemployed_2002', inplace=True)
df_job.drop(columns = 'Unemployed_2003', inplace=True)
df_job.drop(columns = 'Unemployed_2004', inplace=True)
df_job.drop(columns = 'Unemployed_2005', inplace=True)
df_job.drop(columns = 'Unemployed_2006', inplace=True)
df_job.drop(columns = 'Unemployed_2007', inplace=True)
df_job.drop(columns = 'Unemployed_2008', inplace=True)
df_job.drop(columns = 'Unemployed_2009', inplace=True)

In [106]:
df_job.drop(columns = 'Unemployed_2010', inplace=True)
df_job.drop(columns = 'Unemployed_2011', inplace=True)
df_job.drop(columns = 'Unemployed_2012', inplace=True)
df_job.drop(columns = 'Unemployed_2013', inplace=True)
df_job.drop(columns = 'Unemployed_2014', inplace=True)
df_job.drop(columns = 'Unemployed_2015', inplace=True)
df_job.drop(columns = 'Unemployed_2016', inplace=True)
df_job.drop(columns = 'Unemployed_2017', inplace=True)
df_job.drop(columns = 'Unemployed_2018', inplace=True)
df_job.drop(columns = 'Unemployed_2019', inplace=True)
df_job.drop(columns = 'Unemployed_2020', inplace=True)

In [107]:
# Check the revised data set
df_job.head()

FIPS_Code State             Area_name  Unemployment_rate_2000  \
0       1007    AL       Bibb County, AL                     5.4   
1       1009    AL     Blount County, AL                     3.5   
2       1021    AL    Chilton County, AL                     4.3   
3       1073    AL  Jefferson County, AL                     4.0   
4       1115    AL  St. Clair County, AL                     3.8   

   Unemployment_rate_2001  Unemployment_rate_2002  Unemployment_rate_2003  \
0                     6.8                     7.0                     5.9   
1                     3.7                     5.4                     4.6   
2                     4.8                     5.1                     5.0   
3                     4.4                     5.2                     5.5   
4                     4.2                     5.1                     5.2   

   Unemployment_rate_2004  Unemployment_rate_2005  Unemployment_rate_2006  \
0                     5.4                     4.4                     4.2   
1                     4.1                     3.6                     3.2   
2                     4.6                     3.9                     3.6   
3                     5.2                     4.4                     4.0   
4                     4.9                     3.9                     3.5   

   ...  Unemployment_rate_2013  Unemployment_rate_2014  \
0  ...                     8.0                     7.2   
1  ...                     6.4                     6.1   
2  ...                     6.7                     6.2   
3  ...                     6.8                     6.3   
4  ...                     6.2                     5.7   

   Unemployment_rate_2015  Unemployment_rate_2016  Unemployment_rate_2017  \
0                     6.7                     6.5                     4.5   
1                     5.4                     5.4                     4.2   
2                     5.7                     5.5                     4.2   
3                     5.8                     5.7                     4.4   
4                     5.2                     5.2                     4.1   

   Unemployment_rate_2018  Unemployment_rate_2019  Unemployment_rate_2020  \
0                     4.0                     3.1                     6.6   
1                     3.5                     2.7                     4.1   
2                     3.6                     2.7                     5.0   
3                     3.7                     2.9                     6.2   
4                     3.5                     2.7                     4.9   

   Median_Household_Income_2019  Med_HH_Income_Percent_of_State_Total_2019  
0                        47,918                                       92.6  
1                        52,902                                      102.2  
2                        49,692                                       96.0  
3                        54,127                                      104.6  
4                        65,403                                      126.3  

[5 rows x 26 columns]

In [108]:
df_job.shape

(3275, 26)

## 5.2 Data Consistency Checks

In [109]:
# Check statistics of numeric variables
df_job.describe()

FIPS_Code  Unemployment_rate_2000  Unemployment_rate_2001  \
count   3275.000000             3270.000000             3270.000000   
mean   31336.829618                4.540581                5.233119   
std    16321.509704                2.042105                2.228461   
min        0.000000                1.300000                1.600000   
25%    19022.000000                3.200000                3.800000   
50%    30019.000000                4.100000                4.800000   
75%    46100.000000                5.300000                6.100000   
max    72153.000000               17.300000               18.600000   

       Unemployment_rate_2002  Unemployment_rate_2003  Unemployment_rate_2004  \
count             3270.000000             3270.000000             3270.000000   
mean                 5.981193                6.226391                5.879235   
std                  2.344970                2.329511                2.114957   
min                  1.600000                1.900000                1.600000   
25%                  4.500000                4.700000                4.500000   
50%                  5.600000                5.800000                5.500000   
75%                  6.900000                7.300000                6.700000   
max                 19.900000               20.200000               20.200000   

       Unemployment_rate_2005  Unemployment_rate_2006  Unemployment_rate_2007  \
count             3263.000000             3263.000000             3270.000000   
mean                 5.671713                5.152253                5.106116   
std                  2.224239                2.101063                2.150555   
min                  2.000000                1.600000                1.400000   
25%                  4.200000                3.800000                3.700000   
50%                  5.200000                4.800000                4.700000   
75%                  6.500000                5.900000                5.900000   
max                 21.000000               20.700000               20.200000   

       Unemployment_rate_2008  ...  Unemployment_rate_2012  \
count             3270.000000  ...             3272.000000   
mean                 6.032722  ...                8.029034   
std                  2.415970  ...                3.169637   
min                  1.300000  ...                1.100000   
25%                  4.400000  ...                5.900000   
50%                  5.700000  ...                7.700000   
75%                  7.200000  ...                9.600000   
max                 22.600000  ...               27.700000   

       Unemployment_rate_2013  Unemployment_rate_2014  Unemployment_rate_2015  \
count             3272.000000             3272.000000             3272.000000   
mean                 7.580165                6.473839                5.728698   
std                  3.131071                2.866937                2.459260   
min                  1.200000                1.200000                1.800000   
25%                  5.500000                4.700000                4.200000   
50%                  7.200000                6.100000                5.300000   
75%                  9.000000                7.600000                6.600000   
max                 27.400000               26.400000               24.600000   

       Unemployment_rate_2016  Unemployment_rate_2017  Unemployment_rate_2018  \
count             3272.000000             3272.000000             3272.000000   
mean                 5.427109                4.791687                4.272188   
std                  2.353018                2.165926                1.869085   
min                  1.600000                1.500000                1.200000   
25%                  4.000000                3.500000                3.100000   
50%                  5.000000                4.400000                3.900000   
75%                  6.200000                5.400000 

### 5.2.1 Identify any missing/ NaN data

In [110]:
# Check for missing data
df_job.isnull().sum()

FIPS_Code                                     0
State                                         0
Area_name                                     0
Unemployment_rate_2000                        5
Unemployment_rate_2001                        5
Unemployment_rate_2002                        5
Unemployment_rate_2003                        5
Unemployment_rate_2004                        5
Unemployment_rate_2005                       12
Unemployment_rate_2006                       12
Unemployment_rate_2007                        5
Unemployment_rate_2008                        5
Unemployment_rate_2009                        5
Unemployment_rate_2010                        3
Unemployment_rate_2011                        3
Unemployment_rate_2012                        3
Unemployment_rate_2013                        3
Unemployment_rate_2014                        3
Unemployment_rate_2015                        3
Unemployment_rate_2016                        3
Unemployment_rate_2017                  

In [111]:
# Check variables with missing data
df_job_nan = df_job[df_job['Unemployment_rate_2020'].isnull() == True]

In [112]:
df_job_nan

FIPS_Code State                                        Area_name  \
432       72007    PR                       Aguas Buenas Municipio, PR   
433       72009    PR                           Aibonito Municipio, PR   
434       72017    PR                        Barceloneta Municipio, PR   
435       72019    PR                       Barranquitas Municipio, PR   
436       72021    PR                            Bayamon Municipio, PR   
...         ...   ...                                              ...   
3218      72147    PR                            Vieques Municipio, PR   
3222       2201    AK  Prince of Wales-Outer Ketchikan Census Area, AK   
3223       2232    AK            Skagway-Hoonah-Angoon Census Area, AK   
3224       2280    AK              Wrangell-Petersburg Census Area, AK   
3274      72000    PR                                      Puerto Rico   

      Unemployment_rate_2000  Unemployment_rate_2001  Unemployment_rate_2002  \
432                     10.0                    11.9                    13.3   
433                     11.7                    11.9                    14.3   
434                     12.8                    15.1                    15.7   
435                     10.9                    11.3                    13.2   
436                      7.6                     8.4                     9.2   
...                      ...                     ...                     ...   
3218                    13.2                    13.9                    17.8   
3222                    14.1                    15.1                    15.4   
3223                     9.8                    11.6                    12.2   
3224                     9.7                    10.1                    11.2   
3274                    10.1                    11.4                    12.3   

      Unemployment_rate_2003  Unemployment_rate_2004  Unemployment_rate_2005  \
432                     12.9                    11.6                    12.0   
433                     13.8                    12.6                    15.0   
434                     15.3                    12.9                    14.8   
435                     12.6                    11.2                    12.7   
436                      9.1                     7.9                     8.5   
...                      ...                     ...                     ...   
3218                    16.1                    12.4                    11.0   
3222                    14.4                    13.5                    13.2   
3223                    11.8                    13.2                    13.4   
3224                    12.0                    12.4                    10.1   
3274                    12.0                    10.6                    11.3   

      Unemployment_rate_2006  ...  Unemployment_rate_2013  \
432                     11.5  ...                    16.8   
433                     12.7  ...                    17.1   
434                     14.3  ...                    21.5   
435                     11.9  ...                    15.5   
436                      7.9  ...                    10.1   
...                      ...  ...                     ...   
3218                     9.3  ...                    15.9   
3222                    14.3  ...                     NaN   
3223                    12.7  ...                     NaN   
3224                     9.6  ...                     NaN   
3274                    10.5  ...                    14.3   

      Unemployment_rate_2014  Unemployment_rate_2015  Unemployment_rate_2016  \
432                     16.5                    14.6                    14.3   
433                     17.5                    14.6                    14.9   
434                     19.9                    15.2                    14.1   
435                     15.7                    13.2                    12.8   
436                     10.3                     9.3          

__There is overlap in variables with missing data across rows. While unemployment rates could be imputed using linear interpolation, given the missing data represents 2.5% of the total data set, and mainly comes comes from 2020, I took the decision to remove the missing values.__

### 5.2.2 Delete missing/ NaN values

In [113]:
# Delete missing/ NaN values
df_job.dropna(inplace = True)

In [114]:
# Check for any remaining missing data and the shape of the revised data set
df_job.isnull().sum()

FIPS_Code                                    0
State                                        0
Area_name                                    0
Unemployment_rate_2000                       0
Unemployment_rate_2001                       0
Unemployment_rate_2002                       0
Unemployment_rate_2003                       0
Unemployment_rate_2004                       0
Unemployment_rate_2005                       0
Unemployment_rate_2006                       0
Unemployment_rate_2007                       0
Unemployment_rate_2008                       0
Unemployment_rate_2009                       0
Unemployment_rate_2010                       0
Unemployment_rate_2011                       0
Unemployment_rate_2012                       0
Unemployment_rate_2013                       0
Unemployment_rate_2014                       0
Unemployment_rate_2015                       0
Unemployment_rate_2016                       0
Unemployment_rate_2017                       0
Unemployment_

In [115]:
df_job.shape

(3180, 26)

### 5.2.3 Check variable data types

In [116]:
df_job.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3180 entries, 0 to 3273
Data columns (total 26 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   FIPS_Code                                  3180 non-null   int64  
 1   State                                      3180 non-null   object 
 2   Area_name                                  3180 non-null   object 
 3   Unemployment_rate_2000                     3180 non-null   float64
 4   Unemployment_rate_2001                     3180 non-null   float64
 5   Unemployment_rate_2002                     3180 non-null   float64
 6   Unemployment_rate_2003                     3180 non-null   float64
 7   Unemployment_rate_2004                     3180 non-null   float64
 8   Unemployment_rate_2005                     3180 non-null   float64
 9   Unemployment_rate_2006                     3180 non-null   float64
 10  Unemployment_rate_2007  

In [117]:
# Check for mixed data types
for col in df_job.columns.tolist():
  weird = (df_job[[col]].applymap(type) != df_job[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_job[weird]) > 0:
    print (col)

In [118]:
# Convert 'Median_Household_Income_2019' to an integer to aid its use in the analysis
# Remove the comma delimiter from the 'Median_Household_Income_2019' values
df_job.replace(',','', regex=True, inplace=True)

In [119]:
# Check the comma delimiter was removed
df_job.head()

FIPS_Code State            Area_name  Unemployment_rate_2000  \
0       1007    AL       Bibb County AL                     5.4   
1       1009    AL     Blount County AL                     3.5   
2       1021    AL    Chilton County AL                     4.3   
3       1073    AL  Jefferson County AL                     4.0   
4       1115    AL  St. Clair County AL                     3.8   

   Unemployment_rate_2001  Unemployment_rate_2002  Unemployment_rate_2003  \
0                     6.8                     7.0                     5.9   
1                     3.7                     5.4                     4.6   
2                     4.8                     5.1                     5.0   
3                     4.4                     5.2                     5.5   
4                     4.2                     5.1                     5.2   

   Unemployment_rate_2004  Unemployment_rate_2005  Unemployment_rate_2006  \
0                     5.4                     4.4                     4.2   
1                     4.1                     3.6                     3.2   
2                     4.6                     3.9                     3.6   
3                     5.2                     4.4                     4.0   
4                     4.9                     3.9                     3.5   

   ...  Unemployment_rate_2013  Unemployment_rate_2014  \
0  ...                     8.0                     7.2   
1  ...                     6.4                     6.1   
2  ...                     6.7                     6.2   
3  ...                     6.8                     6.3   
4  ...                     6.2                     5.7   

   Unemployment_rate_2015  Unemployment_rate_2016  Unemployment_rate_2017  \
0                     6.7                     6.5                     4.5   
1                     5.4                     5.4                     4.2   
2                     5.7                     5.5                     4.2   
3                     5.8                     5.7                     4.4   
4                     5.2                     5.2                     4.1   

   Unemployment_rate_2018  Unemployment_rate_2019  Unemployment_rate_2020  \
0                     4.0                     3.1                     6.6   
1                     3.5                     2.7                     4.1   
2                     3.6                     2.7                     5.0   
3                     3.7                     2.9                     6.2   
4                     3.5                     2.7                     4.9   

   Median_Household_Income_2019  Med_HH_Income_Percent_of_State_Total_2019  
0                         47918                                       92.6  
1                         52902                                      102.2  
2                         49692                                       96.0  
3                         54127                                      104.6  
4                         65403                                      126.3  

[5 rows x 26 columns]

In [120]:
# Change the data type to an integer
df_job['Median_Household_Income_2019'] = df_job['Median_Household_Income_2019'].astype('int8')

In [121]:
# Check the revised data set
df_job.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3180 entries, 0 to 3273
Data columns (total 26 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   FIPS_Code                                  3180 non-null   int64  
 1   State                                      3180 non-null   object 
 2   Area_name                                  3180 non-null   object 
 3   Unemployment_rate_2000                     3180 non-null   float64
 4   Unemployment_rate_2001                     3180 non-null   float64
 5   Unemployment_rate_2002                     3180 non-null   float64
 6   Unemployment_rate_2003                     3180 non-null   float64
 7   Unemployment_rate_2004                     3180 non-null   float64
 8   Unemployment_rate_2005                     3180 non-null   float64
 9   Unemployment_rate_2006                     3180 non-null   float64
 10  Unemployment_rate_2007  

## 5.3 Check for duplicate values

In [122]:
df_job_dups = df_job[df_job.duplicated()]

In [123]:
df_job_dups

Empty DataFrame
Columns: [FIPS_Code, State, Area_name, Unemployment_rate_2000, Unemployment_rate_2001, Unemployment_rate_2002, Unemployment_rate_2003, Unemployment_rate_2004, Unemployment_rate_2005, Unemployment_rate_2006, Unemployment_rate_2007, Unemployment_rate_2008, Unemployment_rate_2009, Unemployment_rate_2010, Unemployment_rate_2011, Unemployment_rate_2012, Unemployment_rate_2013, Unemployment_rate_2014, Unemployment_rate_2015, Unemployment_rate_2016, Unemployment_rate_2017, Unemployment_rate_2018, Unemployment_rate_2019, Unemployment_rate_2020, Median_Household_Income_2019, Med_HH_Income_Percent_of_State_Total_2019]
Index: []

[0 rows x 26 columns]

# 6.0 Merge data sets

## 6.1 Create common geolocator data for all data sets

__The HUD, Education, and Unemployment data sets all contain FIPS State and County codes, which can be used as primary keys for merging them.  The Gun Violence data set only contains latitude and longitude, so it was necessary to map these coordinates to State and County FIPS codes using State and County shapefiles from the US Census Bureau and the geopandas libary with shapely.geometry. As this process takes a long time to run in Jupyter notebooks, I decided to export the cleaned 'Gun Violence Data' set as a csv file and import it into a different script to carry out the conversion of longitude and latitude values to FIPS Codes. This script is called 'Conversion of Longtitude and Latitude to FIPS Codes and can be found in the 'Scripts' folder of this project.__

__Then, to assist analysis and visualization, I will also use a State, County, and State & County FIPS code mapping tool from the US Unemployment & Education Level data set - which I edited and converted to a .csv file__

### 6.1.1 Convert longitude and latitude values in the Gun Violence data set to FIPS Codes as a revised csv file

In [124]:
# Export the revised Gun Violence Data data set as a csv file to re-import and map to FIPS State and County codes
df_gun.to_csv(os.path.join(path,'2_Data', 'Prepared Data', 'gun_violence_data.csv'))

__This csv file was imported into a new script in a different Jupyter notebook - "Conversion of Longitude and Latitude to FIPS Codes". The result revised data set is then exported as a new csv file, which is imported into this script, below:__

In [125]:
# Import the revised Gun Violence Data data set with State and County FICs codes
df_gun_FIPS = pd.read_csv(os.path.join(path, '2_Data', 'Prepared Data', 'gun_violence_data_FIPS.csv'), index_col=0) 

In [126]:
# Check the revised data set
df_gun_FIPS.head()

date           state city_or_county  latitude  longitude  \
incident_id                                                                   
461105       2013-01-01    Pennsylvania     Mckeesport   40.3467   -79.8559   
460726       2013-01-01      California      Hawthorne   33.9090  -118.3330   
478855       2013-01-01            Ohio         Lorain   41.4455   -82.1377   
478925       2013-01-05        Colorado         Aurora   39.6518  -104.8020   
478959       2013-01-07  North Carolina     Greensboro   36.1140   -79.9569   

             State FIPS Code  County FIPS Code  
incident_id                                     
461105                  42.0               3.0  
460726                   6.0              37.0  
478855                  39.0              93.0  
478925                   8.0               5.0  
478959                  37.0              81.0

In [127]:
# Check for missing data
df_gun_FIPS.isnull().sum()

date                  0
state                 0
city_or_county        0
latitude              0
longitude             0
State FIPS Code     102
County FIPS Code    102
dtype: int64

__For reasons I couldn't determine, 102 lat. and long. values were not converted to FIPS codes (57 were for the same FIPS code). I manually coverted the coordinates to FIPS codes in Excel using the Federal Communications Commission Area APIs (https://geo.fcc.gov/api/census/#!/block/get_block_find), an open-source tool for developers. I also concatenated the State and County FIPs codes before uploading the version of the 'gun_violence_data.csv file to usde for the dataframes merge.__

In [128]:
# Import the corrected Gun Violence Data data set with concatenated State and County FIPS data
df_gun_FIPS = pd.read_csv(os.path.join(path, '2_Data', 'Prepared Data', 'gun_violence_data_FIPS_edit1.csv'), index_col=0) 

In [129]:
# Check the final data set for Gun Violence Data
df_gun_FIPS.head()

incident_id           state city_or_county  latitude  longitude  \
date                                                                          
2013-01-01       461105    Pennsylvania     Mckeesport   40.3467   -79.8559   
2013-01-01       460726      California      Hawthorne   33.9090  -118.3330   
2013-01-01       478855            Ohio         Lorain   41.4455   -82.1377   
2013-01-05       478925        Colorado         Aurora   39.6518  -104.8020   
2013-01-07       478959  North Carolina     Greensboro   36.1140   -79.9569   

            county_&_state_FIPS_Code  
date                                  
2013-01-01                     42003  
2013-01-01                      6037  
2013-01-01                     39093  
2013-01-05                      8005  
2013-01-07                     37081

In [130]:
# Check for any missing values
df_gun_FIPS.isnull().sum()

incident_id                 0
state                       0
city_or_county              0
latitude                    0
longitude                   0
county_&_state_FIPS_Code    0
dtype: int64

### 6.1.2 Import the State, County, and FIPS Cpde csv file to merge with all data sets

In [131]:
# Import the State, County, and FIPS code csv file
df_FIPS_names = pd.read_csv(os.path.join(path, '2_Data', 'Prepared Data', 'State_County_FIPS.csv'), index_col=0) 

In [132]:
df_FIPS_names.head()

state  FIPS Code
county                         
Autauga County    AL       1001
Autauga County    AL       1001
Autauga County    AL       1001
Autauga County    AL       1001
Autauga County    AL       1001

In [133]:
# Reset index to include 'county' as a column in the dataframe
df_FIPS_names.index.name = 'county'
df_FIPS_names = df_FIPS_names.reset_index(0)

In [134]:
# Reset the order of the columns so that 'FIPS Codes' is first

In [135]:
# Confirm the df_FIPS_names dataframe
df_FIPS_names

county state  FIPS Code
0         Autauga County    AL       1001
1         Autauga County    AL       1001
2         Autauga County    AL       1001
3         Autauga County    AL       1001
4         Autauga County    AL       1001
...                  ...   ...        ...
52884   St. Croix Island    VI      78010
52885   St. Croix Island    VI      78010
52886   St. Croix Island    VI      78010
52887    St. John Island    VI      78020
52888  St. Thomas Island    VI      78030

[52889 rows x 3 columns]

In [136]:
# Check the size and datatypes of the dataframe
df_FIPS_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52889 entries, 0 to 52888
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   county     52889 non-null  object
 1   state      52889 non-null  object
 2   FIPS Code  52889 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 1.2+ MB


In [137]:
# Change the datatype of the FIPS Code to a string
df_FIPS_names['FIPS Code'] = df_FIPS_names['FIPS Code'].astype('str')

In [138]:
# Recheck the size and datatypes of the dataframe
df_FIPS_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52889 entries, 0 to 52888
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   county     52889 non-null  object
 1   state      52889 non-null  object
 2   FIPS Code  52889 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB


__I can now remove all geographic/ location data from all data sets, except for the FIPS code, and us the df_FIPS_names to add standard County and State names__

### 6.1.3 Remove non-FIPS Code geographic/ location data from the HUD data set and rename the FIPS Code variable

In [139]:
# Remove non-FIPS location variables from the HUD data set
df_HUD.drop(columns = ['Longitude'], inplace=True)
df_HUD.drop(columns = ['Latitude'], inplace=True)
df_HUD.drop(columns = ['STREET ADDRESS'], inplace=True)
df_HUD.drop(columns = ['CITY'], inplace=True)
df_HUD.drop(columns = ['STATE'], inplace=True)
df_HUD.drop(columns = ['ZIP CODE'], inplace=True)

In [140]:
# Rename the FIPS Code variable in the HUD data set
df_HUD.rename({'COUNTY FIPS CODE': 'FIPS Code'}, axis=1, inplace=True)

In [141]:
# Check the revised HUD data set
df_HUD.head()

HAS ACTIVE FINANCING  FIPS Code
index                                
0                        Y    39041.0
1                        N    18141.0
2                        N    24510.0
3                        N    18025.0
4                        Y    17031.0

In [142]:
# Change the data type of 'FIPS Code' to an integer
df_HUD['FIPS Code'] = df_HUD['FIPS Code'].astype(int)

In [143]:
# Reorder the columns so that 'FIPS Code' is the first column
# Define the column order
column_order = ['FIPS Code', 'HAS ACTIVE FINANCING']

In [144]:
# Rearrange the columns to the defined column order
df_HUD = df_HUD[column_order]

In [145]:
# Check the data type change
df_HUD.head()

FIPS Code HAS ACTIVE FINANCING
index                                
0          39041                    Y
1          18141                    N
2          24510                    N
3          18025                    N
4          17031                    Y

In [146]:
df_HUD.shape

(23598, 2)

In [147]:
# Check the size and datatypes of the revised dataframe
df_HUD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23598 entries, 0 to 23633
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   FIPS Code             23598 non-null  int64 
 1   HAS ACTIVE FINANCING  23598 non-null  object
dtypes: int64(1), object(1)
memory usage: 553.1+ KB


In [148]:
# Change the datatype of the FIPS Code to a string
df_HUD['FIPS Code'] = df_HUD['FIPS Code'].astype('str')

In [149]:
# Recheck the size and datatypes
df_HUD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23598 entries, 0 to 23633
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   FIPS Code             23598 non-null  object
 1   HAS ACTIVE FINANCING  23598 non-null  object
dtypes: object(2)
memory usage: 553.1+ KB


### 6.1.4 Remove non-FIPS Code geographic/ location data from the Gun Violence data set and rename the FIPS Code variable

In [150]:
# Remove non-FIPS location variables from the Gun Violence data set
df_gun_FIPS.drop(columns = ['state'], inplace=True)
df_gun_FIPS.drop(columns = ['city_or_county'], inplace=True)
df_gun_FIPS.drop(columns = ['latitude'], inplace=True)
df_gun_FIPS.drop(columns = ['longitude'], inplace=True)

In [151]:
# Rename the FIPS Code variable in the Gun Violence data set
df_gun_FIPS.rename({'county_&_state_FIPS_Code': 'FIPS Code'}, axis=1, inplace=True)
# Rename the incident_id variable as gun incident ID
df_gun_FIPS.rename({'incident_id': 'gun incident ID'}, axis=1, inplace=True)

In [152]:
# Check the revised Gun Violence Data data set
df_gun_FIPS.head()

gun incident ID  FIPS Code
date                                  
2013-01-01           461105      42003
2013-01-01           460726       6037
2013-01-01           478855      39093
2013-01-05           478925       8005
2013-01-07           478959      37081

In [153]:
df_gun_FIPS.shape

(231754, 2)

__Before moving forward, I need to address the issue that the 'date' variable is treated as an index, rather than a variable column - and then rename it.  To correct this I need to re-set the index of the dataframe.__

In [154]:
# Name the index as 'date'
df_gun_FIPS.index.name = 'date'

In [155]:
# Re-set the index to add the date column to the dataframe as a variable column
df_gun_FIPS = df_gun_FIPS.reset_index(0)

In [156]:
# Rename the 'date' variable as ' date of gun incident'
df_gun_FIPS.rename({'date': 'date of gun incident'}, axis=1, inplace=True)

In [157]:
# Reorder the columns so that 'FIPS Code' is the first column
# Define the column order
column_order = ['FIPS Code', 'gun incident ID', 'date of gun incident']
# Rearrange the columns to the defined column order
df_gun_FIPS = df_gun_FIPS[column_order]

In [158]:
df_gun_FIPS.head()

FIPS Code  gun incident ID date of gun incident
0      42003           461105           2013-01-01
1       6037           460726           2013-01-01
2      39093           478855           2013-01-01
3       8005           478925           2013-01-05
4      37081           478959           2013-01-07

In [159]:
# Check the size and datatypes of the dataframe
df_gun_FIPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231754 entries, 0 to 231753
Data columns (total 3 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   FIPS Code             231754 non-null  int64 
 1   gun incident ID       231754 non-null  int64 
 2   date of gun incident  231754 non-null  object
dtypes: int64(2), object(1)
memory usage: 5.3+ MB


In [160]:
# Change the datatype of the FIPS Code to a string
df_gun_FIPS['FIPS Code'] = df_gun_FIPS['FIPS Code'].astype('str')

In [161]:
# Recheck the size and datatypes
df_gun_FIPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231754 entries, 0 to 231753
Data columns (total 3 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   FIPS Code             231754 non-null  object
 1   gun incident ID       231754 non-null  int64 
 2   date of gun incident  231754 non-null  object
dtypes: int64(1), object(2)
memory usage: 5.3+ MB


### 6.1.5 Remove non-FIPS Code geographic/ location data from the Education data set and rename the FIPS Code variable

In [162]:
# Remove non-FIPS location variables from the Education data set
df_edu.drop(columns = ['State'], inplace=True)
df_edu.drop(columns = ['Area name'], inplace=True)

In [163]:
# Check the revised data set
df_edu.head()

FIPS Code  Percent of adults with less than a high school diploma, 1980  \
0       1007                                               59.5              
1       1009                                               53.9              
2       1021                                               54.0              
3       1073                                               35.3              
4       1115                                               50.1              

   Percent of adults with a high school diploma only, 1980  \
0                                               29.6         
1                                               32.4         
2                                               31.1         
3                                               33.1         
4                                               33.6         

   Percent of adults completing some college (1-3 years), 1980  \
0                                                6.1             
1                                                8.4             
2                                                8.5             
3                                               15.8             
4                                                9.9             

   Percent of adults completing four years of college or higher, 1980  \
0                                                4.9                    
1                                                5.3                    
2                                                6.5                    
3                                               15.8                    
4                                                6.4                    

   Percent of adults with less than a high school diploma, 1990  \
0                                               48.2              
1                                               39.5              
2                                               43.4              
3                                               26.2              
4                                               39.0              

   Percent of adults with a high school diploma only, 1990  \
0                                               33.8         
1                                               34.7         
2                                               32.6         
3                                               28.3         
4                                               32.9         

   Percent of adults completing some college or associate's degree, 1990  \
0                                               13.2                       
1                                               18.8                       
2                                               16.5                       
3                                               25.7                       
4                                               19.6                       

   Percent of adults with a bachelor's degree or higher, 1990  \
0                                                4.7            
1                                                7.0            
2                                                7.5            
3                                               19.9            
4                                                8.5            

   Percent of adults with less than a high school diploma, 2000  \
0                                               36.8              
1                                               29.6              
2                                               33.8              
3                                               19.1              
4                                               28.7              

   Percent of adults with a high school diploma only, 2000  \
0                                               35.7         
1                                               36.0         
2                                               35.8         
3                                               27

In [177]:
# Change the datatype of the FIPS Code to a string
df_edu['FIPS Code'] = df_edu['FIPS Code'].astype('str')

In [194]:
# Check the revised dataframe
df_edu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3260 entries, 0 to 3282
Data columns (total 17 columns):
 #   Column                                                                    Non-Null Count  Dtype  
---  ------                                                                    --------------  -----  
 0   FIPS Code                                                                 3260 non-null   object 
 1   Percent of adults with less than a high school diploma, 1980              3260 non-null   float64
 2   Percent of adults with a high school diploma only, 1980                   3260 non-null   float64
 3   Percent of adults completing some college (1-3 years), 1980               3260 non-null   float64
 4   Percent of adults completing four years of college or higher, 1980        3260 non-null   float64
 5   Percent of adults with less than a high school diploma, 1990              3260 non-null   float64
 6   Percent of adults with a high school diploma only, 1990         

### 6.1.5 Remove non-FIPS Code geographic/ location data from the Unemployment data set and rename the FIPS Code variable

In [164]:
# Remove non-FIPS location variables from the Unemployment data set
df_job.drop(columns = ['State'], inplace=True)
df_job.drop(columns = ['Area_name'], inplace=True)
# Rename the FIPS Code variable
df_job.rename({'FIPS_Code': 'FIPS Code'}, axis=1, inplace=True)

In [165]:
# Check the revised data set
df_job.head()

FIPS Code  Unemployment_rate_2000  Unemployment_rate_2001  \
0       1007                     5.4                     6.8   
1       1009                     3.5                     3.7   
2       1021                     4.3                     4.8   
3       1073                     4.0                     4.4   
4       1115                     3.8                     4.2   

   Unemployment_rate_2002  Unemployment_rate_2003  Unemployment_rate_2004  \
0                     7.0                     5.9                     5.4   
1                     5.4                     4.6                     4.1   
2                     5.1                     5.0                     4.6   
3                     5.2                     5.5                     5.2   
4                     5.1                     5.2                     4.9   

   Unemployment_rate_2005  Unemployment_rate_2006  Unemployment_rate_2007  \
0                     4.4                     4.2                     4.2   
1                     3.6                     3.2                     3.2   
2                     3.9                     3.6                     3.5   
3                     4.4                     4.0                     3.9   
4                     3.9                     3.5                     3.5   

   Unemployment_rate_2008  ...  Unemployment_rate_2013  \
0                     6.0  ...                     8.0   
1                     4.8  ...                     6.4   
2                     5.2  ...                     6.7   
3                     5.6  ...                     6.8   
4                     5.2  ...                     6.2   

   Unemployment_rate_2014  Unemployment_rate_2015  Unemployment_rate_2016  \
0                     7.2                     6.7                     6.5   
1                     6.1                     5.4                     5.4   
2                     6.2                     5.7                     5.5   
3                     6.3                     5.8                     5.7   
4                     5.7                     5.2                     5.2   

   Unemployment_rate_2017  Unemployment_rate_2018  Unemployment_rate_2019  \
0                     4.5                     4.0                     3.1   
1                     4.2                     3.5                     2.7   
2                     4.2                     3.6                     2.7   
3                     4.4                     3.7                     2.9   
4                     4.1                     3.5                     2.7   

   Unemployment_rate_2020  Median_Household_Income_2019  \
0                     6.6                            46   
1                     4.1                           -90   
2                     5.0                            28   
3                     6.2                           111   
4                     4.9                           123   

   Med_HH_Income_Percent_of_State_Total_2019  
0                                       92.6  
1                                      102.2  
2                                       96.0  
3                                      104.6  
4                                      126.3  

[5 rows x 24 columns]

In [178]:
# Change the datatype of the FIPS Code to a string
df_job['FIPS Code'] = df_job['FIPS Code'].astype('str')

In [195]:
# Check the revised dataset
df_job.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3180 entries, 0 to 3273
Data columns (total 24 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   FIPS Code                                  3180 non-null   object 
 1   Unemployment_rate_2000                     3180 non-null   float64
 2   Unemployment_rate_2001                     3180 non-null   float64
 3   Unemployment_rate_2002                     3180 non-null   float64
 4   Unemployment_rate_2003                     3180 non-null   float64
 5   Unemployment_rate_2004                     3180 non-null   float64
 6   Unemployment_rate_2005                     3180 non-null   float64
 7   Unemployment_rate_2006                     3180 non-null   float64
 8   Unemployment_rate_2007                     3180 non-null   float64
 9   Unemployment_rate_2008                     3180 non-null   float64
 10  Unemployment_rate_2009  

## 6.2 Merge the HUD and Gun Violence data sets with the State and County names data set

In [166]:
df_HUD_gun = df_HUD.merge(df_gun_FIPS, on = 'FIPS Code')

In [167]:
df_HUD_gun.head()

FIPS Code HAS ACTIVE FINANCING  gun incident ID date of gun incident
0     39041                    Y           140619           2014-05-30
1     39041                    Y           151524           2014-06-27
2     39041                    Y           221284           2014-11-08
3     39041                    Y           267323           2014-12-22
4     39041                    Y           406527           2015-09-02

In [168]:
df_HUD_gun.shape

(17897715, 4)

In [169]:
df_HUD_gun.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17897715 entries, 0 to 17897714
Data columns (total 4 columns):
 #   Column                Dtype 
---  ------                ----- 
 0   FIPS Code             object
 1   HAS ACTIVE FINANCING  object
 2   gun incident ID       int64 
 3   date of gun incident  object
dtypes: int64(1), object(3)
memory usage: 682.7+ MB


In [170]:
df_HUD_gun['gun incident ID'] = df_HUD_gun['gun incident ID'].astype ('str')

### 6.2.2 Merge with the State/County Names data set

In [171]:
#df_HUD_gun_place = df_HUD_gun.merge(df_FIPS_names, on = 'FIPS Code')

__I am unable to merge the State/County Names data set with the merged HUD + Gun Violence dataframes. Each time I try the kernel dies. I have tried converting FIPS Codes datatype from INT64 to Strings to reduce the file size, but I have not been able to make it work.  I am looking to my Tutor and Mentor for suggestions on how to do this.

## 6.3 Merge the Education and Unemployment data sets with the State and County names data set

In [179]:
df_edu_job = df_edu.merge(df_job, on = 'FIPS Code')

In [180]:
# Check the merged dataframe
df_edu_job.head()

FIPS Code  Percent of adults with less than a high school diploma, 1980  \
0      1007                                               59.5              
1      1009                                               53.9              
2      1021                                               54.0              
3      1073                                               35.3              
4      1115                                               50.1              

   Percent of adults with a high school diploma only, 1980  \
0                                               29.6         
1                                               32.4         
2                                               31.1         
3                                               33.1         
4                                               33.6         

   Percent of adults completing some college (1-3 years), 1980  \
0                                                6.1             
1                                                8.4             
2                                                8.5             
3                                               15.8             
4                                                9.9             

   Percent of adults completing four years of college or higher, 1980  \
0                                                4.9                    
1                                                5.3                    
2                                                6.5                    
3                                               15.8                    
4                                                6.4                    

   Percent of adults with less than a high school diploma, 1990  \
0                                               48.2              
1                                               39.5              
2                                               43.4              
3                                               26.2              
4                                               39.0              

   Percent of adults with a high school diploma only, 1990  \
0                                               33.8         
1                                               34.7         
2                                               32.6         
3                                               28.3         
4                                               32.9         

   Percent of adults completing some college or associate's degree, 1990  \
0                                               13.2                       
1                                               18.8                       
2                                               16.5                       
3                                               25.7                       
4                                               19.6                       

   Percent of adults with a bachelor's degree or higher, 1990  \
0                                                4.7            
1                                                7.0            
2                                                7.5            
3                                               19.9            
4                                                8.5            

   Percent of adults with less than a high school diploma, 2000  ...  \
0                                               36.8             ...   
1                                               29.6             ...   
2                                               33.8             ...   
3                                               19.1             ...   
4                                               28.7             ...   

   Unemployment_rate_2013  Unemployment_rate_2014  Unemployment_rate_2015  \
0                     8.0                     7.2                     6.7   
1                     6.4                     6.1                     5.4   
2                     6.7                 

In [181]:
df_edu_job.shape

(3172, 40)

In [182]:
df_HUD_edu_job = df_HUD.merge(df_edu_job, on = 'FIPS Code')

In [183]:
df_HUD_edu_job.head()

FIPS Code HAS ACTIVE FINANCING  \
0     39041                    Y   
1     39041                    N   
2     39041                    Y   
3     39041                    N   
4     39041                    Y   

   Percent of adults with less than a high school diploma, 1980  \
0                                               25.2              
1                                               25.2              
2                                               25.2              
3                                               25.2              
4                                               25.2              

   Percent of adults with a high school diploma only, 1980  \
0                                               42.9         
1                                               42.9         
2                                               42.9         
3                                               42.9         
4                                               42.9         

   Percent of adults completing some college (1-3 years), 1980  \
0                                               13.2             
1                                               13.2             
2                                               13.2             
3                                               13.2             
4                                               13.2             

   Percent of adults completing four years of college or higher, 1980  \
0                                               18.6                    
1                                               18.6                    
2                                               18.6                    
3                                               18.6                    
4                                               18.6                    

   Percent of adults with less than a high school diploma, 1990  \
0                                               15.6              
1                                               15.6              
2                                               15.6              
3                                               15.6              
4                                               15.6              

   Percent of adults with a high school diploma only, 1990  \
0                                               34.3         
1                                               34.3         
2                                               34.3         
3                                               34.3         
4                                               34.3         

   Percent of adults completing some college or associate's degree, 1990  \
0                                               23.7                       
1                                               23.7                       
2                                               23.7                       
3                                               23.7                       
4                                               23.7                       

   Percent of adults with a bachelor's degree or higher, 1990  ...  \
0                                               26.4           ...   
1                                               26.4           ...   
2                                               26.4           ...   
3                                               26.4           ...   
4                                               26.4           ...   

   Unemployment_rate_2013  Unemployment_rate_2014  Unemployment_rate_2015  \
0                     5.3                     4.1                     3.6   
1                     5.3                     4.1                     3.6   
2                     5.3                     4.1                     3.6   
3                     5.3                     4.1                     3.6   
4                     5.3                     4.1                     3.6   

   Unemployment_rate_2016  Unemployment_rate_2017  Unemp

# 7.0 Export revised dataframes

In [188]:
df_FIPS_names.to_csv(os.path.join(path, '2_Data', 'Prepared Data', 'State_County_FIPS_cleaned.csv')) 

In [185]:
df_HUD_gun.to_pickle(os.path.join(path, '2_Data', 'Prepared Data', 'HUD_Gun Violence.pkl')) 

In [189]:
df_HUD.to_csv(os.path.join(path, '2_Data', 'Prepared Data', 'HUD_cleaned.csv'))

In [190]:
df_gun_FIPS.to_csv(os.path.join(path, '2_Data', 'Prepared Data', 'Gun Violence_cleaned.csv')) 

In [191]:
df_HUD_edu_job.to_pickle(os.path.join(path, '2_Data', 'Prepared Data', 'HUD_Edu_Unemployed.pkl'))

In [192]:
df_edu.to_csv(os.path.join(path, '2_Data', 'Prepared Data', 'Education_cleaned.csv'))

In [193]:
df_job.to_csv(os.path.join(path, '2_Data', 'Prepared Data', 'Unemployment_cleaned.csv')) 